### ISSUE TITLE
Strategy for namespace packages

### ISSUE THREAD

**Issue by taldcroft** [sot/skare3#10]
Related to #9, the pip 10.0+ does not correctly support namespace packages via the pkgutil mechanism.  AFAIK there is no way to install a namespace package into an isolated directory, so things break if you uninstall.  I explicitly confirmed this with https://github.com/pypa/sample-namespace-packages.  I think the pip folks just don't care about this.  Sticking with pip < 10.0 is fine for now.

At some point when we are further down the Py3 road and it makes sense, we can consider the happy step of changing all our namespace packages to be "native", meaning there is no `__init__.py` in the namespace package dir.  This works only for Py3, but has the big advantage that everything just works, including setting PYTHONPATH to include a dev namespace package.

In this paradigm for some repos we would need to fork a `py2` branch which keeps the `__init__.py` and would receive  backports when needed.  I think `Chandra.cmd_states`, `Chandra.Time`, and `Ska.engarchive` are the only ones with any possibility of *needing* a backport.  Most others should be fine where they are for Py2.

No immediate action from this, just recording my thoughts.

**Comment by jeanconn** [comment]
I think this is done.
