### ISSUE TITLE
Migrate all namespace packages to "native" namespace packages

### ISSUE THREAD

**Issue by taldcroft** [sot/skare3#104]
Python 3.3 add support for [native namespace packages](https://packaging.python.org/guides/packaging-namespace-packages/#native-namespace-packages), where there is no `__init__.py` required in the namespace root (i.e. `Ska.` or `Chandra.`).

This has benefits:
- Allows testing of namespace packages with PYTHONPATH.  Even though spinning up a test environment is *much* easier now with skare3, using PYTHONPATH is even easier for quick work.
- Simplifies build recipes by not requiring a distinction between namespace and not-namespace packages.
- Minor 
  - Makes package file path more beautiful
  - Should eliminate easy_install.pth (or similar) path files, which behave in an abominable and always confusing way.

Relatedly, the [official recommendation](https://conda.io/docs/user-guide/tutorials/build-pkgs.html#writing-the-build-script-files-build-sh-and-bld-bat) for the `build.sh` is:
```
$PYTHON setup.py install --single-version-externally-managed --record=record.txt
```
Our version has a bunch of stuff that was historically useful/required, but it isn't clear how much of that still applies.  Should re-evaluate.

Addressing this issue would scratch an itch I have suffered for many years.  It wouldn't be entirely trivial since every namespace package and (potentially) every `build.sh` would need update, and this would require 4.x versions of every namespace package.  Nevertheless, I'd like to do this when there is a good opportunity.

For feasibility and testing, I have verified using two simple namespace packages `Ska.Shell` and `Ska.File` that the following works within this paradigm:
- `PYTHONPATH` successfully puts the package into the path (even with same package installed into environment)
- `pip install` successfully installs and uninstalls the namespace packages.  In particular going from both installed to just one installed, and then zero installed, all behave as expected.
- `conda install` successfully installs and uninstalls the namespace packages.  In particular going from both installed to just one installed, and then zero installed, all behave as expected.

**Comment by taldcroft** [comment]
Answering the "should re-evaluate" somewhat:
```
pip install --no-deps --verbose --no-binary :all: --no-index
```
I think `--no-deps` can stay although none of our packages specify requirements that `pip` would consider including.  

`--verbose` is benign, probably don't need it now.

It seems like `--no-binary :all:` and `--no-index` are no-ops with `--no-deps`.  OTOH I probably had a reason for putting them there the first time.

**Comment by jeanconn** [comment]
I think this is done, though it remains a good reference for pip commands etc.
