### ISSUE TITLE
Update sot/vv_trending to 0.1.0

### ISSUE THREAD

**Issue by javierggt** [sot/skare3#1143]
Includes the following merges:
- PR [#5](https://github.com/sot/vv_trending/pull/5): Python Package
- PR [#4](https://github.com/sot/vv_trending/pull/4): Update the plot range to be from 2015 and add safe mode line
- PR [#3](https://github.com/sot/vv_trending/pull/3): Add plot of Z rms vs n100 frac
- PR [#2](https://github.com/sot/vv_trending/pull/2): Rotate year ticklables and fit them on 2d plot

**Comment by jeanconn** [comment]
Installed to flight via environment-non-fsds.yml
