### ISSUE TITLE
Update sot/fss_check to 1.0.0

### ISSUE THREAD

**Issue by javierggt** [sot/skare3#1144]
Includes the following merges:
- PR [#21](https://github.com/sot/fss_check/pull/21): Add workflows
- PR [#16](https://github.com/sot/fss_check/pull/16): Refactor and overhaul checking code
- PR [#17](https://github.com/sot/fss_check/pull/17): FSS-B trending for pitch < 135 deg
- PR [#15](https://github.com/sot/fss_check/pull/15): New bad time interval for 2023:044/047 safe modes
- PR [#14](https://github.com/sot/fss_check/pull/14): Exclude bad times near 2022:294 safe mode

**Comment by jeanconn** [comment]
It sounds like @taldcroft installed this so the conda package does not need to be installed "in something".

**Comment by taldcroft** [comment]
@jeanconn - not quite.. I just installed the package to my /export/tom miniconda for final testing and to get it running immediately. But doing a conda install of this package to ska3 flight is what I was imagining as a follow-up when possible.

**Comment by jeanconn** [comment]
Until we figure out what to do for non-fsds, it seems like conda installing the single package to flight would be benign.

**Comment by taldcroft** [comment]
Sounds like a plan. I really do like taking a lighter approach to non-fsds packages, meaning that they are not pinned by a metapackage and updating is less effort.

**Comment by jeanconn** [comment]
Installed to flight via environment-non-fsds.yml.
