### ISSUE TITLE
Include update for kadi 3.16.4

### ISSUE THREAD

**Issue by taldcroft** [sot/skare3#115]
https://github.com/sot/kadi/pull/126 is a high priority for release to flight.

**Comment by jeanconn** [comment]
Do you want it for the MATLAB release too?

**Comment by jeanconn** [comment]
Also, needs release.

**Comment by taldcroft** [comment]
Yes on including in MATLAB release.

**Comment by taldcroft** [comment]
Right forgot that Mark made a build. So maybe not...
