### ISSUE TITLE
ska3-masters environment needs data update

### ISSUE THREAD

**Issue by jeanconn** [sot/skare3#1151]
**Description**
ska3-masters environment needs data update.

It looks like /export/jgonzale/github-workflows/miniconda3/envs/ska3-masters/data has some old directories instead of links (used for testing at previous times) and doesn't have the new data/acis_tables/ 

This looks to be causing a failure in the new acis_tables parse_cm test.

**Comment by javierggt** [comment]
The only difference between `/proj/sot/ska3/test/data` (which is link to from ska3-masters) and `/proj/sot/ska3/flight/data` is in `attitude_error_mon` and `arc3`. The `chandra_models` directory is not a link, but it is a separate local repo and it is at the same revision, so no difference there.

Which one is the problem?

**Comment by javierggt** [comment]
I just created the symlink for `acis_tables` in `/proj/sot/ska3/test/data`
