### ISSUE TITLE
Improve setup.py version fetching in all packages as needed

### ISSUE THREAD

**Issue by jeanconn** [sot/skare3#118]
See

https://github.com/sot/skare3/issues/116#issuecomment-469751239

**Comment by jeanconn** [comment]
Regarding putting the helper functions `read`, and `read_version` from

https://github.com/pypa/pip/blob/master/setup.py#L14

into testr.  Two things:

1) testr right now is an optional dependence in most of our builds.  Do we want to require it?
2) those routines would need a little customization for a non-local non-global `here`

And on a different track, would it make just as much sense to use 4. instead of 1. from:
https://packaging.python.org/guides/single-sourcing-package-version/
?

It seems that we could then just customize __version__ to be read/assigned from VERSION.

**Comment by taldcroft** [comment]
I'm still bitter that setuptools_scm turned out to be heavier than we'd like, but reviewing https://github.com/sot/eng_archive/pull/157 it seemed to be in a working state.

Most of the "single-source" ideas including `VERSION` are not actually single-source given our package build process.

**Comment by jeanconn** [comment]
sot/eng_archive#157 looked to be in a working state, but I saw it didn't get pushed and looks to not complete github build tests.  Is the latter just due to the dual-package nature at this point?

**Comment by jzuhone** [comment]
What about versioneer?

https://github.com/warner/python-versioneer

It does require one to install their package in the Python stack, but after you run it on your package to generate the version-handling code, there are no new dependencies.

**Comment by taldcroft** [comment]
See https://github.com/sot/sparkles/pull/129
