### ISSUE TITLE
Need some process for getting sherpa linux build onto GRETA

### ISSUE THREAD

**Issue by taldcroft** [sot/skare3#12]
Can we re-host the appropriate linux and Mac builds in our area and avoid the `conda config --add channels sherpa`?

**Comment by jeanconn** [comment]
I don't think that is a problem.  I think we just copy in the package and re-index.  I also don't know that we'd have to do anything for Mac, but could add that one too.

**Comment by taldcroft** [comment]
If we do the Mac side then we avoid the need for adding the sherpa channel altogether.  So we make sherpa as an official part of the Ska3 configured distro, albeit OTS.  The downside is small, you just need to record your process for getting the package and putting it into the right place.

**Comment by jeanconn** [comment]
Granted, for GRETA, the web channel doesn't work, so I assume for process we'll just be copying all of the conda repo over there anyway.

**Comment by jeanconn** [comment]
Regard re-hosting... do we need something in skare3 to support this (a ska3-sherpa skare3 package that fetches the sherpa conda package from someplace and puts it in our repo)?  Or are we fine with just copying the files and reindexing manually as needed.

**Comment by taldcroft** [comment]
I'm fine with a one-time copy for now.  We can refine process later as needed.

**Comment by jeanconn** [comment]
Regarding the Mac side, I don't see any Py3 packages, so I don't know if we'll ask for them or build them.

https://anaconda.org/CXC/sherpa/files

**Comment by jzuhone** [comment]
@jeanconn I think you have the wrong URL:

https://anaconda.org/sherpa/sherpa/files

**Comment by taldcroft** [comment]
Whatever the process ends up being should be captured in https://github.com/sot/skare3/wiki/Ska3-runtime-environment-for-maintainers.  That will close this issue.

**Comment by jeanconn** [comment]
The process was a single copy of the package into our ska3-conda repo and a re-index.   I don't know if it really deserves a place in the docs, but can do so.  The process for Mac will be to figure out which one of the packages we want and do the same.

The sherpa packages will just get sync'd to greta with the other packages per the directions for syncing to GRETA.

**Comment by taldcroft** [comment]
> The process was a single copy of the package into our ska3-conda repo and a re-index. I don't know if it really deserves a place in the docs, but can do so. 

Yes!  I don't know how to do that without digging around and googling, so please make it so.  An important new concept in skare3 is to carefully document every little step at a level where the steps can be followed with minimal domain knowledge.

**Comment by jeanconn** [comment]
My point was that I think the digging will be the same next time (no idea where the next sherpa package will come from).  But we can hope for the best.

**Comment by jeanconn** [comment]
I think https://github.com/sot/skare3/wiki/Ska3-runtime-environment-for-maintainers#sherpa-packages is sufficient at this point.

**Comment by taldcroft** [comment]
Looks good!  I got a little confused by flow so I moved the Sherpa stuff to the end of that section.

**Comment by jeanconn** [comment]
Understood.  And yeah, flow is a problem and there's enough stuff that I don't know if we'll want to link out of the one doc to others.
