### ISSUE TITLE
zlib + pytables 3.4.2 + matplotlib = segfault on savefig when tables imported first

### ISSUE THREAD

**Issue by jeanconn** [sot/skare3#126]
zlib + pytables 3.4.2 + matplotlib = segfault on savefig when tables imported first (zlib does not need to be imported for things to go wrong).

It looks like the workarounds are to import matplotlib before tables or import zlib before matplotlib.   Looks like this is fixed in newer versions of pytables and/or zlib.

**Comment by jeanconn** [comment]
@taldcroft  I'm not sure if there is a more useful place to put this as a "gotcha" with our current ska3-flight.

**Comment by taldcroft** [comment]
Can we upgrade to the newer version(s) without the problem?

**Comment by jeanconn** [comment]
I think we have the last pytables before everything breaks, but I also confess I don't remember where things were with pytables issues.

**Comment by jeanconn** [comment]
Yeah, pytables 3.4.2 is the last one available for our old versions of things.  Else we would have updated already to try to fix #84 .  I can look again at our own source-built conda package or we can let the versions of things start to differ much more significantly between 32bit and 64bit.

**Comment by javierggt** [comment]
This issue becomes irrelevant after shiny, so will close.

No idea if this was ever fixed, but does somebody care now?

**Comment by jeanconn** [comment]
Similar to the other issues you are closing (thanks!) I think it makes sense to assume these are fixed and we can always open new issues.  This one is the kind of thing that was order dependent and weird... but apparently I didn't write up a test and there also isn't enough here to really help us if it turns up again.

**Comment by javierggt** [comment]
yes, I figure these things could "in principle" happen, but might be unlikely considering so much changed.
