### ISSUE TITLE
Update sot/fss_check to 1.0.1

### ISSUE THREAD

**Issue by javierggt** [sot/skare3#1299]
## What's Changed
* Add job with --days-recent=360 to task_schedule by @taldcroft in https://github.com/sot/fss_check/pull/22

**Full Changelog**: https://github.com/sot/fss_check/compare/1.0.0...1.0.1

Includes the following merges:
- PR [#22](https://github.com/sot/fss_check/pull/22): Add job with --days-recent=360 to task_schedule

**Comment by jeanconn** [comment]
Technically this non-fsds package is listed as a package requiring PCAD approval on changes as well, but since the update is just to the task schedule, and came as a request from PCAD, I'm going to install this without additional review.

**Comment by jeanconn** [comment]
I built this manually for python 3.10, put it in flight channel (and indexed), and installed in HEAD ska3/flight.
