### ISSUE TITLE
xija.core extension does not compile on CentOS-6 or CentOS-7

### ISSUE THREAD

**Issue by taldcroft** [sot/skare3#130]
On CentOS-6 and 7 I see the same result below  No problems on CentOS-5 and MacOSX (High Sierra).
```
web-kadi-test$ ska3
ska3-web-kadi-test$ python setup.py test
running test
running egg_info
creating xija.egg-info
writing xija.egg-info/PKG-INFO
writing dependency_links to xija.egg-info/dependency_links.txt
writing entry points to xija.egg-info/entry_points.txt
writing top-level names to xija.egg-info/top_level.txt
writing manifest file 'xija.egg-info/SOURCES.txt'
reading manifest file 'xija.egg-info/SOURCES.txt'
writing manifest file 'xija.egg-info/SOURCES.txt'
running build_ext
building 'xija.core' extension
creating build
creating build/temp.linux-x86_64-3.6
creating build/temp.linux-x86_64-3.6/xija
gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/proj/sot/ska3/flight/include/python3.6m -c xija/core.c -o build/temp.linux-x86_64-3.6/xija/core.o
In file included from /proj/sot/ska3/flight/include/python3.6m/Python.h:30:0,
                 from xija/core.c:3:
/usr/include/string.h:544:5: error: unknown type name ‘__locale_t’
     __locale_t __loc)
     ^
/usr/include/string.h:548:18: error: unknown type name ‘__locale_t’
      size_t __n, __locale_t __loc)
```

**Comment by taldcroft** [comment]
Discussed at MATLAB tools WG.  Got commitment (in principle) to drop support for 32-bit linux and move to using MATLAB linux only on 64-bit platforms.  FOT will request that FST prioritize the upgrade of chimchim(s) to CentOS >= 6, but this might still be a while given FST tasking.

**Comment by mbaski** [comment]
FST has agreed to upgrade the chimchim machine coming from Hampshire to CentOS 7.  This may happen as soon as early July, but they have a lot on their plate.

**Comment by jzuhone** [comment]
Is there a status on a resolution for this issue?

**Comment by taldcroft** [comment]
No resolution AFAIK.  Maybe you could take a crack at this?  To update things slightly, we will need to provide support for CentOS-6 and 7 (64-bit) going forward, so you should target 6 for compiling.

**Comment by jzuhone** [comment]
I'd be happy to look at it, but I guess the question is are we blocked any longer on this by machine updates?

**Comment by taldcroft** [comment]
And looking up the thread, @jeanconn noted that the problem is likely the old gcc.  You might bundle this into the bigger project of making a new ska3-flight with the latest releases for all core packages.  (That is not *necessary*, of course, but we had talked about this).

Current status is our MATLAB tools ska3-matlab branch won't get to drop 32-bit/CentOS-5 until around Mar. 2020, but it might be a bit sooner.  INT is working on the migration of all GRETA workstations to 64-bit CentOS-6.  That, along with getting MATLAB tools running 2019a on that platform, are the milestones for the Mar 2020 date.

So I have been pondering letting ska3-flight diverge significantly from ska3-matlab in the interim, and @mbaski was on board in principle.  (Does that mean a ska3-core-matlab?).

So we (you) could at least start earnest work on the big update to ska3-flight and core to get recent releases and make things like xija actually build.

**Comment by taldcroft** [comment]
> So it is a reasonable question if we want to start to let the conda environments diverge (and allow ourselves to build more modern environments on CentOS6 or 7) or keep everything frozen for CentOS5 back compatibility.

That's Jean's question from May 8.  So I think we are getting more serious about the divergent environments solution.

**Comment by jzuhone** [comment]
Sorry, I'm being a bit dense here. We will still have the old gcc on the CentOS 6/7 machines, correct? So we need to change something other than the gcc? Just

**Comment by jeanconn** [comment]
Not dense.   I'm not that completely clear on it either at this point; right now to keep building happy on the old machines we explicitly installed `gcc` in skare3 (and use it as both a build and run dependency I believe).  The hope for the future would be that all of the dependencies that call out gcc that way can be removed or updated.  I would hope that the system gcc on the CentOS6 machines could be used for anything that needs a gcc, otherwise we'd go with an updated version from conda (in the new channels).

**Comment by taldcroft** [comment]
As expected, xija builds and passes tests on CentOS-6 (fido).  The session below is from a clean (no Ska3) environment.

```
fido$ cd ~/git/xija
fido$ gcc --version
gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-23)
Copyright (C) 2010 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

fido$ which gcc
/usr/bin/gcc

fido$ git clean -fxd
Removing .cache/
...
Removing xija/version.pyc

fido$ /proj/sot/ska3/flight/bin/python setup.py build_ext --inplace
running build_ext
building 'xija.core' extension
creating build
creating build/temp.linux-x86_64-3.6
creating build/temp.linux-x86_64-3.6/xija
gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/proj/sot/ska3/flight/include/python3.6m -c xija/core.c -o build/temp.linux-x86_64-3.6/xija/core.o
creating build/lib.linux-x86_64-3.6
creating build/lib.linux-x86_64-3.6/xija
gcc -pthread -shared -L/proj/sot/ska3/flight/lib -Wl,-rpath=/proj/sot/ska3/flight/lib,--no-as-needed build/temp.linux-x86_64-3.6/xija/core.o -L/proj/sot/ska3/flight/lib -lpython3.6m -o build/lib.linux-x86_64-3.6/xija/core.cpython-36m-x86_64-linux-gnu.so
copying build/lib.linux-x86_64-3.6/xija/core.cpython-36m-x86_64-linux-gnu.so -> xija

fido$ /proj/sot/ska3/flight/bin/python setup.py test
running test
running egg_info
creating xija.egg-info
writing xija.egg-info/PKG-INFO
writing dependency_links to xija.egg-info/dependency_links.txt
writing entry points to xija.egg-info/entry_points.txt
writing top-level names to xija.egg-info/top_level.txt
writing manifest file 'xija.egg-info/SOURCES.txt'
writing manifest file 'xija.egg-info/SOURCES.txt'
running build_ext
copying build/lib.linux-x86_64-3.6/xija/core.cpython-36m-x86_64-linux-gnu.so -> xija
====================================================================== test session starts =======================================================================
platform linux -- Python 3.6.2, pytest-3.2.1, py-1.4.34, pluggy-0.4.0
rootdir: /data/baffin/tom/git/xija-clean, inifile: setup.cfg
plugins: remotedata-0.3.0, openfiles-0.3.0, doctestplus-0.1.3, arraydiff-0.2
collected 9 items                                                                                                                                                 

xija/tests/test_models.py .........

======================================================================== warnings summary ========================================================================
None
  [pytest] section in setup.cfg files is deprecated, use [tool:pytest] instead.

-- Docs: http://doc.pytest.org/en/latest/warnings.html
============================================================= 9 passed, 1 warnings in 18.25 seconds ==============================================================
```

**Comment by taldcroft** [comment]
Same experiment succeeds on CentOS-7 (kady), now with gcc 4.8.5.

**Comment by javierggt** [comment]
I think it is fair to say this is not an issue anymore. Right? Closing it. Reopen a new one if necessary.

**Comment by taldcroft** [comment]
Awesome, getting rid of problems like this has been a huge driver for shiny. It is so wonderful to see this finally come to pass with issues getting closed.
