### ISSUE TITLE
Update sot/obc_rate_noise_plots to 1.0.1

### ISSUE THREAD

**Issue by javierggt** [sot/skare3#1338]
## What's Changed
* Add __init__.py (and update build workflows) by @jeanconn in https://github.com/sot/obc_rate_noise_plots/pull/6

**Full Changelog**: https://github.com/sot/obc_rate_noise_plots/compare/1.0.0...1.0.1

Includes the following merges:
- PR [#6](https://github.com/sot/obc_rate_noise_plots/pull/6): Add __init__.py (and update build workflows)

**Comment by jeanconn** [comment]
Installed
