### ISSUE TITLE
Mac builds aren't working from acisops org

### ISSUE THREAD

**Issue by jeanconn** [sot/skare3#1364]
**Description**

See https://github.com/acisops/acis_thermal_check/actions/runs/9165351214/job/25198727329)

I suspect acisops/skare3 needs workflow updates to match what we have in sot/skare3 .

For 2024.5 I just built manually.

**Comment by javierggt** [comment]
I fixed this, but for the record:

The acisops/skare3 repo should just mimic sot/skare3. You are also a member of acisops, and I believe you can commit.

I have a local copy of skare3 where I added acisops/skare3 as a remote, then I just do

```
git push acisops
```
(or something like that)

**Comment by jeanconn** [comment]
I'm a member not an owner of acisops.

**Comment by javierggt** [comment]
You don't need to be an owner to commit. All members of acisops have write access to it.
