### ISSUE TITLE
ska_version special-cases ska3-flight but not ska3-matlab

### ISSUE THREAD

**Issue by jeanconn** [sot/skare3#143]
ska_version special-cases ska3-flight but not ska3-matlab

It might be useful to have some kind of special handling of ska3-matlab as well around

https://github.com/sot/skare3/blob/63b11bf42556d08cb29e364c4dc982388ad49b2a/pkg_defs/ska3-template/bin/ska_version#L36

**Comment by javierggt** [comment]
This seems like a legitimate issue. Do we want this? The level of effort seems small.
