### ISSUE TITLE
Add mica 3.18 to ska3-flight

### ISSUE THREAD

**Issue by taldcroft** [sot/skare3#144]

**Comment by jeanconn** [comment]
I've updated this to 3.18 and I had started to use milestones but if you prefer tags that's fine.  I was also planning for this for tomorrow and the others for the week after.

**Comment by taldcroft** [comment]
It can actually be both. I just want something that is very visible (milestones are not) and easy for me or John Z to tag to clearly mark pending package updates.  Then Ska release manager can assign a milestone to the specific release you want to target.  What about three labels: "Package update", "Flight", "MATLAB"?

**Comment by taldcroft** [comment]
Also, an issue can only have one milestone, so in cases where we are updating both flight and MATLAB at the same time, milestones don't tell the whole story.

All of this is part of trying to get PRs merged and then make sure the updated packages actually get into Ska3 without relying on release manager to remember (by having the package dev open and tag the issue here).
