### ISSUE TITLE
Migrate kadi web server to Ska3

### ISSUE THREAD

**Issue by taldcroft** [sot/skare3#15]
This may or may not be a challenge, but will depend on systems compiling a `mod_wsgi` plugin for us.  🤞

**Comment by jeanconn** [comment]
What are the actions for skare3 for this?

**Comment by taldcroft** [comment]
Not clear.  I agree this issue is not really helping anything.  That bigger picture migration is not going to be forgotten, as I do that work it will be obvious if skare3 changes are required.
