### ISSUE TITLE
ska3 update troubles on macOS

### ISSUE THREAD

**Issue by jzuhone** [sot/skare3#158]
I recently tried updating ska packages on a local macOS installation and got this:

```
(ska3) [jzuhone@dhcp-131-142-152-199:~] $ conda update -c $ska3conda --all
Collecting package metadata (current_repodata.json): done
Solving environment: failed
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - aspect/ska3-conda/osx-64::ska3-core==2018.08.13=0 -> cryptography==1.8.1
  - aspect/ska3-conda/osx-64::ska3-core==2018.08.13=0 -> tk==8.5.18

Current channels:

  - https://icxc.harvard.edu/aspect/ska3-conda/osx-64
  - https://icxc.harvard.edu/aspect/ska3-conda/noarch
  - https://conda.anaconda.org/sherpa/osx-64
  - https://conda.anaconda.org/sherpa/noarch
  - https://conda.anaconda.org/conda-forge/osx-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://conda.anaconda.org/intel/osx-64
  - https://conda.anaconda.org/intel/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

Is this because we're pinning to versions of packages that are no longer available in the normal channels?

**Comment by jzuhone** [comment]
After doing some digging I think that this is the issue. I can submit a PR to update the package versions for macOS only, but what are our guidelines for doing so?

**Comment by jeanconn** [comment]
If you want a full dev version with a combination of modern packages and ska packages, I think we would need to rebuild the ska3-dev metapackage and you'd install from that.

Should probably talk about what your use case is.  The ska3-flight and ska3-core metapackages are really just configured now to get old/tested versions of packages that will work on 32 bit CentOS.

**Comment by jeanconn** [comment]
I'm also sure what version of conda itself you are using or what you wanted to update (did you really want a go at updating everything in this use case?).  I don't use "update --all" in our use cases at present.

**Comment by jeanconn** [comment]
ska3-flight 2019.07.01 should at least be installable though, either with the old default channels that we're using in the maintainers docs, or with our copy of those packages in the core-pkg-repo dir (I think).

```
channels:
  - https://icxc.harvard.edu/aspect/ska3-conda
  - https://icxc.harvard.edu/aspect/ska3-conda/core-pkg-repo
```

**Comment by taldcroft** [comment]
> I don't use "update --all" in our use cases at present.

Maybe the issue is that what you want to do to bring your local conda up to date with current configured flight is:
```
conda update -c $ska3conda ska3-flight
```
That works for me on my mac.

**Comment by taldcroft** [comment]
Indeed there is no mention of *maintaining* your Ska3 environment in our docs https://github.com/sot/skare3/wiki/Ska3-runtime-environment-for-users.

**Comment by jeanconn** [comment]
> That works for me on my mac.

Though what does your channel list look like at this point?  I haven't played with removing both our old channels and the core-pkg-repo cache of those old packages.

**Comment by taldcroft** [comment]
I have no `.condarc`.

**Comment by jeanconn** [comment]
OK, so what is the built-in channel list from your version of conda?

**Comment by taldcroft** [comment]
I think it's pkgs/main and pkgs/free, based on channels that supply packages if I create a full new env.

**Comment by jzuhone** [comment]
Well, this is weird. I did update conda (to version 4.7.5) on my machine, and had ska3 as an environment in that conda stack, so I thought that was perhaps the reason. I am not able to install a new ska3 environment from scratch on this conda installation. 

So I tried setting up a separate Miniconda installation in a different place using the version of the script which we specified in the docs (4.3.21), but apparently I cannot use that conda to do anything (any conda command silently dies). I've tried this on two macs with the same behavior. So it looks like the two installations don't play nice with each other. 

I'd prefer not to have my main conda installation be stuck back at the earlier version for non-ska things, so I'm not sure what to do here.

**Comment by jeanconn** [comment]
> but apparently I cannot use that conda to do anything (any conda command silently dies). 

So that's certainly interesting.  With regard to playing nice together, what is your impression about why they need to?  Is there a path collision of some kind from .bashrc or the like?  I figured they would and could be independent.

**Comment by jzuhone** [comment]
I think there's a collision in the files that conda uses, e.g. `.condarc` or the `.conda` directory. Trying to see if I can change their names now.

**Comment by jzuhone** [comment]
I had an option enabled in my `.condarc` which was not compatible with the old conda: `channel_priority: disabled`. That was the issue.

**Comment by jeanconn** [comment]
Great!  Good sleuthing and thanks!  So one step closer in our understanding.

**Comment by jzuhone** [comment]
Now getting these errors:

```
[jzuhone@pannenberg:~] $ conda create --channel $ska3conda --name ska3 ska3-flight
Fetching package metadata ...............
Solving package specifications: .

InstallError: Error: 'conda' can only be installed into the root environment

[jzuhone@pannenberg:~] $ conda create --channel $ska3conda --name ska3 ska3-core
Fetching package metadata ...............
Solving package specifications: .

InstallError: Error: the following specs depend on 'conda' and can only be installed
into the root environment: ska3-core

[jzuhone@pannenberg:~] $
```

**Comment by jeanconn** [comment]
Ah.  OK so that's a bug that I introduced in the 2019.07.01.  
I couldn't remember why we didn't have conda as a package in the ska3-core list, but you've identified the reason.

**Comment by jzuhone** [comment]
Yeah, I found the same issue just now on a fresh Linux installation also.

**Comment by jeanconn** [comment]
A "root" install should be fine (which has been our use case for ska3/flight and my testing) but a env install would break per the error.

**Comment by jeanconn** [comment]
I would also assume that ska3-flight=2019.06.19 with the latest ACIS pieces would still work (doesn't have my conda flub).

**Comment by jzuhone** [comment]
Yes, that works.

**Comment by jeanconn** [comment]
Also, I don't know if it is useful for you @jzuhone, but supposedly root conda install can also have a ".condarc".  It isn't clear from the docs how inheritance works (looks like maybe the root version wins) but I don't know if for your setup it might make sense for either your ska installation or your "main" installation to use the root-installed dot-condarc?
