### ISSUE TITLE
Add information about how to update or maintain environment

### ISSUE THREAD

**Issue by jeanconn** [sot/skare3#161]
Add information about how to update or maintain environment

I'm not sure about use cases here yet.

Thus far I've just been doing "conda install ska3-flight=2019.07.01" as my update process.

**Comment by jeanconn** [comment]
Related to #158

**Comment by taldcroft** [comment]
Is there anything wrong with `conda update -c $ska3conda ska3-flight` as now suggested in:
https://github.com/sot/skare3/wiki/Ska3-runtime-environment-for-users#maintaining-ska3-runtime-environment ?

Finding that most-recent version number is not exactly easy for end users.

**Comment by jeanconn** [comment]
I wasn't suggesting that the user needed the version number, I was noting that for maintaining ska3/flight I have not been using or testing user installation methods.  I don't know what other things to test or what caveats to mention or if we should just leave it alone.

Also, I took this as an issue from #158 because I didn't know that you added the new suggestion for update process at the bottom of the runtime-environment-for-users. :smile:

**Comment by javierggt** [comment]
This issue is a bit vague. It seems the documentation available works for people. I suggest creating one post-shiny docs issue, with a specific list of things to do.
