### ISSUE TITLE
Should we use more pinning?

### ISSUE THREAD

**Issue by jeanconn** [sot/skare3#162]
I was trying to somewhat pin conda itself at version 4.3.21 by adding it to ska3-core thus making it obvious that it is required by ska3-flight.  That didn't work, but my effort was there to try to prevent conda from updating it, as a newer version of conda was apparently in the old channels.  And since we hadn't be using "pinning" explicitly, the mechanism open to me was this small web of dependencies in the metapackages.

As @taldcroft noted, right now use of this web of dependencies means if you try to install a package that conflicts with our metapackages, the solver recommends removing the metapackages.

Do we want to explicitly pin to prevent this (adding packages and versions in conda-meta/pinned in environments)?  I haven't tested, but I'd assume that having ska3-flight in pinned would prevent the solver, even for old conda 4.3.21, from trying to uninstall it as a part of environment update.  I don't know if the pin file requires versions, but I think it will respect the syntax of the other tools (pin at greater than version etc).

**Comment by javierggt** [comment]
This issue is a bit vague. It is 1.5 years old and had no answers ever. It seems the current setup works for people. Closing. Reopen if necessary.
