### ISSUE TITLE
Update pyyaks to latest version

### ISSUE THREAD

**Issue by taldcroft** [sot/skare3#176]
Version not updated nor tagged, just a reminder that this package has been updated and should go into the next flight release.

**Comment by jeanconn** [comment]
I'm getting a little confused.  So the package update tag is to track that this could use update and remind us to have a conversation about it.  At today's conversation, I thought we decided that acdc should go and that was it.  But here you've said this should go in "next flight release".  Do you want to brief it this week then, or is the "package update" a reminder that it should go in *a* flight release?

**Comment by taldcroft** [comment]
I started reviewing merged PRs and found this one.  It's going to go in a flight release at some point, so I don't see any particular reason to delay.
