### ISSUE TITLE
Update kadi to 4.18.1

### ISSUE THREAD

**Issue by taldcroft** [sot/skare3#178]
Includes 

https://github.com/sot/kadi/pull/134: Stop pushing to ftp in regular processing
https://github.com/sot/kadi/pull/140: Fix PEP8 and flake8 and clean Py2-only cruft #140

PR 134 is technically in the existing kadi 4.18 release, but that was not installed so we can brief this vs kadi 4.17.

**Comment by jeanconn** [comment]
I think we could legitimately tag the kadi in master now as 4.18.1 (with pep8 fixes) and try this again.

**Comment by taldcroft** [comment]
:+1:
