### ISSUE TITLE
Update ska3-flight for 2019-08-12 release

### ISSUE THREAD

**Issue by jeanconn** [sot/skare3#182]
Update ska3-flight for 2019-08-12 release

So is this looking like

acdc, pyyaks, and removing nbpresent?

#145 / #154 
#176 
#173 

Anything else to go this week?

**Comment by jeanconn** [comment]
Thoughts @taldcroft ?  I'm not sure what would make sense for a blurb for the pyyaks update if you want me to draft a LR announcement.

**Comment by taldcroft** [comment]
pyyaks: 

Added a method to make this utility package, which provides a way of defining structured data directories, more convenient in Python 3.6+.  Specifically, context values can be used directly in any method that takes a os.PathLike object, e.g. Path or os.path methods. In this way it is not required to use the .abs or .rel properties everywhere.

Added a unit test for the new functionality and confirmed existing unit tests pass.

**Comment by taldcroft** [comment]
This list looks good for this week.

**Comment by taldcroft** [comment]
Oh yeah, and add tensorflow and keras.  :-)

**Comment by jeanconn** [comment]
Apparently I'll finally need to update my mac to high sierra...

**Comment by jeanconn** [comment]
I'm cutting the nbpresent update for now (just merged and reverted, related to https://github.com/sot/skare3/pull/173#issuecomment-521298650 )
