### ISSUE TITLE
A production not-Perl metapackage?

### ISSUE THREAD

**Issue by jeanconn** [sot/skare3#188]
After installing acdc on GRETA ska3/flight, I wondered, perhaps there are more packages like this that do not really need to go in ska3-flight but belong in production?

We can think more about this and make a new metapackage if needed (or rename ska3-perl to ska3-production).

**Comment by taldcroft** [comment]
:+1: on renaming ska3-perl to ska3-production.

About acdc, I can see the point there, though acdc does provide processing utilities that could be useful in generic ACA analysis.  In particular the different algorithms for combining quadrant readouts into cal images, e.g. one at a time or median filtering.  That's the sort of thing I would do standalone.

**Comment by jeanconn** [comment]
So maybe we have some more interest in this, though figuring out which packages belong in a new ska3-production package is somewhat not trivial.  

I *think* this would mean on the Perl side, for example, we'd want ska3-perl (or some other name) to have the minimal set for starcheck to work and ska3-production to have the rest of the Perl stuff plus any isolated packages that are only useful on HEAD.

**Comment by taldcroft** [comment]
I would favor an incremental approach that let's us move forward now without getting stuck by non-trivial decisions.  In other words get the low-hanging fruit with  an initial PR:
- Add aca_hi_bgd
- Move acdc from flight to production
- Any other completely uncontroversial packages.

**Comment by jeanconn** [comment]
OK. I just thought even here you'd said there was value in keeping acdc in ska3-flight for the algorithms for combining quadrants.

**Comment by taldcroft** [comment]
Yes, my former self had more insight. The point is just to make some kind of progress forward without overthinking it too much. It doesn't matter all that much. Making ska-production is fine, or just tossing another package into ska3-flight will only make it negligibly bigger and that's fine. Your choice.

**Comment by javierggt** [comment]
Old issue, more than 2 years old. I think this discussion just died out.

In this issue you even agreed to rename ska3-perl to ska3-production. Two years later it has not happened and I do not see it happening yet 😄 I'm sure that can be considered again, but this discussion should be closed.

**Comment by jeanconn** [comment]
Well, we did continue the discussion even up to October.  I suppose I don't know if open discussion best live in closed or open issues...

**Comment by javierggt** [comment]
Feel free to reopen it if it is an ongoing discussion.
