### ISSUE TITLE
Define platform test requirements / platform support

### ISSUE THREAD

**Issue by taldcroft** [sot/skare3#196]
Test requirements have been accruing to include combinations of CentOS 5,6,7 production, 6,7 root not production, and 6,7 non-root + OSX root and non-root, + CentOS5 32 production, + Windows whatever.  We need to make this manageable.

Automated testing is probably in our future, but for now here is a proposed list:

- **CentOS5-64 production**: still used on chimchim.  No ETA to drop but working on it.
- **CentOS6-64 production**: still used on kadi/fido.  Working on moving the kadi web
   service to a VM and upgrading kadi to CentOS7.  ETA 2-4 weeks.  Could do the same for
   fido and drop CentOS6-64 as a test requirement.
- **CentOS5-32 production**: still used for GRETA MATLAB. No ETA to drop but working on it.

<hr>

- **CentOS7-64 production**: baseline platform going forward.
- **CentOS7-64 non-production / non-root with bash**: seems that non-root is a more stringent test.  Also, the user docs only reference this option.  CentOS 5 and 6 for non-production not formally supported.
- **OSX non-production / non-root with bash**: same deal as for CentOS7.

The ones above the line will go away at some point.

**Comment by taldcroft** [comment]
For MacOS I would say High Sierra and Catalina are supported at this time.  In general I would propose to support current and previous OS release.  For integration testing, if we are choosing one version (current or previous), it seems like the current release is more likely to break things.  That is certainly the case right after the new OS release.  For cases where binary packages are changing then we should try to test both versions.

**Comment by jeanconn** [comment]
So should that be Mojave and Catalina?
