### ISSUE TITLE
Convert pip build.sh scripts to setup.py

### ISSUE THREAD

**Issue by jeanconn** [sot/skare3#20]
See discussion in #19

**Comment by jeanconn** [comment]
It will probably be worth digging in a bit to see how the installs differ.   Also see #18 for more discussion.

**Comment by jeanconn** [comment]
Looks like we if we stick with pip it should also have "--ignore-installed" in our version.  I just ran into the issue where apparently pip it wouldn't let me make a conda package of Python module at a version because that package was installed in my environment at that version.  Unlikely overall but annoying.

**Comment by taldcroft** [comment]
At some point we will be maintaining only Py3 versions of our namespace packages, at which point we can use [native namespace packages](https://packaging.python.org/guides/packaging-namespace-packages/#native-namespace-packages).  At that point we don't need `--egg` for those, FWIW.  Or we can just use `setup.py install --single-version-externally-managed`.

**Comment by javierggt** [comment]
This was one of the first things fixed in shiny, right?
