### ISSUE TITLE
Update Chandra.cmd_states > 3.14.2

### ISSUE THREAD

**Issue by jeanconn** [sot/skare3#213]
Packages still needs update in ska3-matlab because it lags ska3-flight. Note that the test fixed in 3.14.2 (fails due to not having /data/mpcrit1 available) still fails in ska3-matlab as of version 2019.10.02 because this package has not been updated

**Comment by jeanconn** [comment]
These three package updates that are marked MATLAB only are marked as such because they packages are already in ska3-flight.   I wanted new issues to track places where that the ska3-matlab versions are still behind because we haven't had a more general update of the ska3-matlab packages (and have had "please only make minimal changes to ska3 python in support of this next release" type releases).  

It is a reasonable question on if this issue approach has value contrasted with an approach that opens one issue that says "update ska3-matlab to latest ska3-flight versions", but for me it had value in that every time I ran ska_testr on ska3-matlab and the Chandra.cmd_states test still failed I could see here an issue that reminded me "oh, that package still isn't up-to-date on the ska3-matlab side so that's why".

What additional context or text would make sense for @taldcroft ?  For me MATLAB-only issues *without* additional text meant "package still out of date on MATLAB".

**Comment by javierggt** [comment]
Jean's answer has to do with what I was saying in the email. Since you have used a single branch for both MATLAB and Flight, you need to keep track of when you made a release for one and not the other (and which packages are not included for each). Otherwise you have to dig into the history to see if a particular package already made it to MATLAB/Flight

**Comment by jeanconn** [comment]
@taldcroft per my question above for this one, now that we've talked a bit about these MATLAB-only issues in person (thanks!), I'm still not clear what context would make sense for the issue description?  "Packages still needs update in ska3-matlab because it lags ska3-flight.  Note that ACIS test fixed in 3.14.2 still fails in ska3-matlab as of version 2019.10.02 because this package has not been updated"?

**Comment by taldcroft** [comment]
Sure.  Just a reminder that simply lagging behind ska3-flight is not a reason to open an issue, there needs to be some actual driver for an update.  I might turn this around an ask if we need to include all the ACIS load review tools in ska3-matlab.  Eliminating those would presumably eliminate the failing test.  Do you remember where to find the package list and Mark's build script for Windows?  I thought it was in an email but I can't dig it up.

**Comment by jeanconn** [comment]
OK, and that isn't a reminder, as I don't think we'd defined a policy.  I thought lagging was enough of an issue but if you want a driver for it to belong in ska3-matlab too we can manage it that way and discuss via issues as such.  Regarding turning it around, this is Chandra.cmd_states and its own ACIS-contributed test is the one that fails on missing data that I updated in https://github.com/sot/cmd_states/pull/44.  If you wanted to pull Chandra.cmd_states from ska3-matlab I don't immediately recall what our cmd_states dependencies are at this point because we didn't do a full/real dependency tree for conda, but I think you'd at least need to pull out the pieces used by kadi if you want kadi in ska3-matlab.

Honestly, we had a bit of the "what belong in ska3-matlab" discussion at one point and I was a fan of reducing it to be xija, proseco, sparkles and whatever required by them, but the dependency tree blossoms.  I also seem to recall that Mark actually liked having more of the rest of the modules pieces available in the Ska Python environment that they were "getting for free" as included with the matlab tools, though I suppose it is a different question if that should just be supported with standalone ska3 instead of via the matlab tools install.

**Comment by jeanconn** [comment]
Link to build stuff in separate email as I don't think we wanted those links on github.

**Comment by taldcroft** [comment]
I did not suggest removing Chandra.cmd_states, I was suggesting all the ACIS load review packages like `acisfp_check` and so on.  (I wrote a comment earlier with the diff below but forgot to press "Comment", and that would be where the "policy" started).  Here are the diffs (with expected ones removed) and so right now we there are issues open for 4 out of 12 packages that are lagging.  AFAIK, just one of those is "substantive" (cmd_states), so that leads me to think that in practice we should only tag those substantive cases.  The mica update might be tagged in an issue as *requiring* starcheck 13.5, at least if these are the changes that sloshed the starcheck parser, a move that I do officially regret at this point.
```
HEAD is now at 3579ae3 Merge pull request #217 from sot/2019.10.28
neptune$ diff pkg_defs/ska3{-flight,-matlab}/meta.yaml 
16,17c15
<     - acisfp_check ==v2.7.0
---
>     - acisfp_check ==v2.4.0
19c17
<     - acis_thermal_check ==v2.9.0
---
>     - acis_thermal_check ==v2.8.0
21,22c19,20
<     - chandra_aca ==4.27
<     - chandra.cmd_states ==3.15
---
>     - chandra_aca ==4.25.2
>     - chandra.cmd_states ==3.14.2
26,27c24,25
<     - dea_check ==v2.3.0
<     - dpa_check ==v2.4.0
---
>     - dea_check ==v2.2.0
>     - dpa_check ==v2.3.0
30c28
<     - kadi ==4.18.1
---
>     - kadi ==3.16.4
32,33c30,31
<     - mica ==4.19
<     - parse_cm ==3.5
---
>     - mica ==3.16
>     - parse_cm ==3.4
36c34
<     - pyyaks ==4.4
---
>     - pyyaks ==3.3.5
40c38
<     - ska.dbi ==4.0
---
>     - ska.dbi ==3.8.2
48c46
<     - ska_sync ==4.4
---
>     - ska_sync ==4.2
54d51
<     - starcheck ==13.4
```

**Comment by jeanconn** [comment]
Yes, I saw you did not explicitly suggest removing Chandra.cmd_states, you just said "eliminating those would presumably eliminate the failing test" and I tried to communicate that the test is a Chandra.cmd_states test so I don't immediately see how removing the ACIS load review packages would help that particular issue.

**Comment by jeanconn** [comment]
Will be updated to 3.15 in matlab 2019_210 targeted release.  Closing issue as not helpful
