### ISSUE TITLE
Update Ska.engarchive to 4.47.2

### ISSUE THREAD

**Issue by taldcroft** [sot/skare3#215]
https://github.com/sot/eng_archive/releases/tag/4.47.2

**Comment by jeanconn** [comment]
Looks like we'll want 4.47 by the time we do this.

**Comment by jeanconn** [comment]
@taldcroft Did you want to push 4.47.2 this to ska3-flight tomorrow or are you going to wait for another more public release until the possible pyyaks issue is resolved?

**Comment by taldcroft** [comment]
@javierggt @jeanconn - this is ready for release this week.
