### ISSUE TITLE
Update find_attitude to 3.2.1

### ISSUE THREAD

**Issue by jeanconn** [sot/skare3#224]
Initial Python 3 compatible release:
https://github.com/sot/find_attitude/releases/tag/3.2

**Comment by taldcroft** [comment]
Consider getting this into the MATLAB 2019_210 release for experimental use on FOT laptops (and potentially integration to MATLAB tools)? The data file it requires is "only" 1.3 Gb.

**Comment by jeanconn** [comment]
I'm going to take this off the milestone because it looks like it breaks things just now https://github.com/sot/kadi/issues/145

**Comment by jeanconn** [comment]
This became 3.3.2
