### ISSUE TITLE
Update to modern packages and conda

### ISSUE THREAD

**Issue by jeanconn** [sot/skare3#225]
This is a rehash of  #170 

It seems like we have these requirements:

ska3 environment with Python >= 3.7, up-to-date astropy, numpy >= 1.17.

Which platforms are required?  
   - OSX >= High Sierra
   - CentOS7 64
   - CentOS6 64

If we are making a more modern environment, is there the expectation that we'll eventually be able to upgrade production HEAD /proj/sot/ska3/flight to that environment?  If so, do we need to be able to do that in-place with incremental installations, or will we be allowed to do a clean install of a modern conda?

With regard to testing and validation, are we going to just require that, say, the ACIS models look about right?  Or do we needed detailed numeric checks?

**Comment by jeanconn** [comment]
Tagging @taldcroft @javierggt @jzuhone

**Comment by jeanconn** [comment]
Status:  I tried to do an in-place update to a modern conda on my High Sierra laptop and ended up with unsatisfiable dependencies in an empty/base env.  Next I was planning to install a modern conda from a modern conda installer in a new area, start over with a clean .condrc, and see if I could get a reasonably-functional ska3-dev with modern numpy etc.

**Comment by jeanconn** [comment]
Aside:  @taldcroft it looked like there wasn't a astropy package in the modern continuum channels built for Python 3.8.

**Comment by taldcroft** [comment]
Yeah, it seems to take several months for the conda repos to fully populate after a new release.  Another core dependency that is missing (last time I checked) is the HDF5 lib.

So this can all move forward with Py 3.7 but with fingers crossed that Py 3.8 can be used in the end without substantial changes.

**Comment by taldcroft** [comment]
Sadly we need to support CentOS-6 for at least 2 years, maybe longer.

**Comment by taldcroft** [comment]
I don't have any reservations about doing a full reinstall once we are ready.  I'm not surprised that the in-place strategy has issues.  I can't say for sure if the reinstall will be easy or some pitfalls will become apparent, but we can figure it out.

**Comment by jzuhone** [comment]
@jeanconn @taldcroft what about conda-forge? does it not have packages updated? I find that typically it is far ahead of the conda main channel

**Comment by taldcroft** [comment]
About Mac, I have been updating all my platforms to Mojave recently.  I think that might be a reasonable minimum, but not totally clear.

**Comment by jeanconn** [comment]
Regarding conda-forge, I had figured that if we didn't require any special stacks of packages, we didn't need to introduce more possible package builders to our stack for ska3.  But of course willing to look at this if it will win us more flexibility without causing other problems.

**Comment by jzuhone** [comment]
my admittedly anecdotal opinion is that most people seem to be using conda-forge as their main source for package updates instead of the conda main channels, which are typically woefully behind and seem to be so because of conda-forge itself.

**Comment by taldcroft** [comment]
@jzuhone - good point, that works (at least for h5py/hdf5 and astropy).  Maybe we can use conda-forge for development work, assuming main will eventually catch up.

**Comment by taldcroft** [comment]
@jeanconn - it's a little painful for you and maybe contrary to the global design of conda, but I really like using the small list of packages in $ska3conda/core-pkg-repo.  It makes everything go super fast and dependencies resolve more clearly.

Using conda-forge in general is going to make everything sloooww, I think.  I'm not sure if they have made progress in resolving the "Solving environment takes forever" issue when using forge.

**Comment by taldcroft** [comment]
Which might suggest a new direction of hosting all of our of core packages in the main $ska3conda.  Just a thought...

**Comment by taldcroft** [comment]
> is there the expectation that we'll eventually be able to upgrade production HEAD /proj/sot/ska3/flight to that environment?

YES!

**Comment by jeanconn** [comment]
With regard to conda-forge, even if we use it as another source of packages, I would push to have a local copy of each package that we use in ska3-flight/ska3-core* kept in our "core-pkg-repo".  I also think that is the only way we're going to be able to do updates on chimchim / cheru.

There's a separate question on if it still makes sense to keep the "we built" package in one repo and the "came from somebody else" packages in a different repo (which is what we do now with ska3conda and ska3conda/core-pkg-repo).  We can hash that out some more.

**Comment by taldcroft** [comment]
> With regard to testing and validation, are we going to just require that, say, the ACIS models look about right? Or do we needed detailed numeric checks?

We're going to delegate testing and validation where possible.  In the case of ACIS, we will rely on the ACIS team to ensure the new environment is acceptable for performing their load review and other operational tasks.

**Comment by jzuhone** [comment]
> Which might suggest a new direction of hosting all of our of core packages in the main $ska3conda. Just a thought...

I would be for this. It would be a lot more predictable.

**Comment by jeanconn** [comment]
With regard to delegation:  Yes,  shooting to talk about this with @jzuhone, but I ended up pushing off the meeting I had scheduled on this today and figured brainstorming here would help to refine a plan if needed (both on requirements and testing).

With regard to "It would be a lot more predictable" I don't know what that means.

**Comment by taldcroft** [comment]
> With regard to "It would be a lot more predictable" I don't know what that means.

When doing conda installs in a dev ska3, I do find it wants to change packages in ways that I can't understand.  Like openssl is always going in one direction or another.  It *seems* like if we have every package first in our repo, then those little variations might go away.  But I have no data to support that...

**Comment by jzuhone** [comment]
> With regard to "It would be a lot more predictable" I don't know what that means.

If we build our own packages for NumPy, h5py, etc. then ideally we would install everything from our own channel and not use any other channels at all.

**Comment by taldcroft** [comment]
> If we build our own packages for NumPy, h5py, etc. then ideally we would install everything from our own channel and not use any other channels at all.

The idea was to *copy* binary packages from other channels, not make them ourselves.  I definitely want to avoid *building* everything from scratch.

**Comment by jzuhone** [comment]
@taldcroft yes, that makes sense.

**Comment by jeanconn** [comment]
Regarding the "predictable" thing, OK, so my question was really about if we needed to combine our core-pkg-repo with the top level repo, but that seems irrelevant to whatever behaviors are have or may be unpredictable for you Tom.  I might need more detail on whatever weirdnesses you see (and of course, they may all change with newer versions of conda itself which include various options for prioritizing packages).

**Comment by taldcroft** [comment]
I would turn it around and ask what is the downside of combining.  Basically I always include the core-pkg-repo, except when have forgotten that name and am too impatient to go look it up again in the magic place in the docs.  I find using the core-pkg-repo highly beneficial and so I think all our users should always just get that by default.  UNLESS there is a real downside.

**Comment by jeanconn** [comment]
OK.  So the original idea was that by keeping them separate we'd have more flexibility to do exactly what I'm doing now while building this dev version... telling conda to prefer our ska packages in non-core things, but to now use a continuum repo for core things instead of our core-pkg-repo.   And that way if we have a specific reason for overriding a core package, that custom package can live in our ska packages (which is what we've done) and that preference can easily persist through updates to ska3-dev.

Then again, we never got off the ground with the ska3-dev idea, so this is all somewhat in the weeds at this point. 

I also recall that there are a few package management issues; I can't easily tell if the packages I've grabbed are noarch or binary or whatever.  But will need to fiddle to see how the software helps us satisfy requirements.  

So it would be good to continue to refine requirements.  With regard to core-pkg-repo, my current requirement was:

Must have a copy of all packages used in ska3-flight/ska3-core in a local conda repo.

**Comment by jeanconn** [comment]
What's the plan for the namespace packages again?  If we move to "python setup.py install" as our build process for all the Python packages  are we all set and do not require the version of pip < 10?

**Comment by taldcroft** [comment]
Handling of namespace packages (i.e. whether to remove the `Ska/__init__.py`) can go either way.  The plan is to use `python setup.py install` everywhere in any case, so we can remove the (ancient) pip version requirement.  Since pip and setuptools are always bundled with `python`, we basically don't need to worry about them in any requirements.

If we leave the namespace package `__init__.py` files in place, then leave that `build` option `preserve_egg_dir: yes`.  If we remove all the init.py files then we don't need to preserve the egg dir.  (I'm 90% sure that will work and that I tested it, but that needs confirmation).

**Comment by jeanconn** [comment]
I think we may end up with some separate ska3 installations to support, say, Replan Central / aca_egse /whatever which use the Perl from skare3-static built with old conda.  I doubt we want those Perl packages in a modern production ska (bringing old gcc etc) and I don't know level of effort to bother to try to rebuild them with modern conda and fewer ancient dependencies.

**Comment by jeanconn** [comment]
Then again, I'm not sure if task_schedule will work with the Perl in the default channel either, so I suppose that suggests we need some modern Perl or a some new tools to replace task_schedule.

**Comment by jeanconn** [comment]
Regarding continuous building for integration testing, I'm seeing stuff in the current docs about cross compiling actually working (specifically building binary packages on linux for macOS), so that's very exciting!

**Comment by taldcroft** [comment]
About continuous building, GitHub actions has support for linux, MacOS and windows VMs, so that seems like a straightforward and well-supported path.
https://github.com/actions/create-release

"Publishing" the resultant package to eventually get onto the HEAD network is not quite as clear to me but I'm sure there is a way.

**Comment by taldcroft** [comment]
> I'm not sure if task_schedule will work with the Perl in the default channel

`task_schedule3` works fine with our custom-built perl 5.26 in ska3, so it would be surprising if we couldn't make that work with the conda-supplied perl 5.26.  But I have been surprised before.

**Comment by jeanconn** [comment]
I've got all custom paths in our custom perl etc.  I don't disagree that we could make it work, I just don't know yet if it would really be easier than going the other way.

**Comment by jeanconn** [comment]
Regarding github actions, awesome!  And I suppose since we only have a few private packages we wouldn't come close to using up our "allowance" of minutes.  I am still curious if the cross compiling works out of the box if that might win us something.

**Comment by taldcroft** [comment]
Don't forget that we can pay whatever it takes even if we end up using a lot of time.  From what I can see there is no support for cross-compiling to Windows, so the cross-compiling option seems less interesting to me.

But really, wouldn't you much rather hit the "Publish release" button on GitHub and then discover 10 minutes later that it is all done?

**Comment by taldcroft** [comment]
> I've got all custom paths in our custom perl etc. I don't disagree that we could make it work, I just don't know yet if it would really be easier than going the other way.

Going the "other way" sounds messy and not quite future-proof, but I'll confess I don't fully get what that option would entail.  Maybe just try first the (success-oriented) strategy of making a nice clean solution, with the minimum requirement that starcheck and task_schedule3 run.    `aca_movie.pl` and `splat.pl` will get retired in favor of `aca_view`, so this may reduce the dependency tree in perl.  Can we finally drop `pgplot` ?!?  The `timelines` perl code will either need support or migration to Python.

If you run into problems that introduce significant new complexity instead of simplification, then stop and we can talk (with diagrams on the board explaining the "other way").

**Comment by jeanconn** [comment]
Regarding pgplot, sure! I think that dependence goes away if we don't need aca_movie and splat.

**Comment by jeanconn** [comment]
Also wait, what is the "(success-oriented) strategy of making a nice clean solution"?

**Comment by taldcroft** [comment]
Success-oriented means to assume it will work out and not spend time forecasting possible problems, instead just dive in and try.

**Comment by taldcroft** [comment]
Clean solution means not maintaining multiple production environments.

**Comment by jeanconn** [comment]
Closed by shiny promotion.
