### ISSUE TITLE
Update kadi to 4.19

### ISSUE THREAD

**Issue by taldcroft** [sot/skare3#229]
Update to version 4.19:

https://github.com/sot/kadi/pull/139 : Update_cmds fixes for py3
https://github.com/sot/kadi/pull/138 : Fix ingest of non-load commands during a load stoppage (anomaly)
https://github.com/sot/kadi/pull/146 : Migrate update_cmds task_schedule to ska3 idiom
https://github.com/sot/kadi/pull/147 : Update mid-manvr test to use column comparisons and isclose
https://github.com/sot/kadi/pull/152 : Add ACIS raw-mode SI modes to ACIS states 
https://github.com/sot/kadi/pull/143 : Py3 server with + event/cmd cron jobs processing with django 3.0

Highlights of 143:
- Make the django server run with Python 3 and django 3.0
- Make the events update work on Python 3
- Add `obsid` as a standard field for telemetry-based events
- Change name of event database file from `events.db3` to `events3.db3`.  New file and schema are not compatible with previous version.
- Flake8 changes

**Comment by jeanconn** [comment]
This became kadi 5.0 which is fine.
