### ISSUE TITLE
Update acdc to 4.4

### ISSUE THREAD

**Issue by taldcroft** [sot/skare3#233]
- https://github.com/sot/acdc/pull/42 - Add acdc_check_cal script.

(BTW the Flight / MATLAB package update distinction does not really apply any more, I think).

**Comment by jeanconn** [comment]
It depends.  Do you want to try to use issues to note that acdc 4.4 will be out of date on the matlab side?

**Comment by taldcroft** [comment]
No. It is built into our process that Flight will normally be ahead of MATLAB for some packages.  I can do `opendiff pkg_defs/ska3-{matlab,flight}/meta.yaml` at any time to see the diffs.

**Comment by jeanconn** [comment]
Closed by #231
