### ISSUE TITLE
Update django to 3.0.x

### ISSUE THREAD

**Issue by taldcroft** [sot/skare3#238]
Kadi 4.19 requires django 3.0+

**Comment by jeanconn** [comment]
I was figuring on the django 2.2 update for shiny.  If you want it before, we'll need to build it on centos5.

**Comment by taldcroft** [comment]
Django is pure Python.  What problem are you anticipating?

**Comment by jeanconn** [comment]
I a) did not know it was pure Python and b) expect everything to be difficult.

**Comment by taldcroft** [comment]
Fair enough.  The django update has been rather painful from the kadi web server perspective, but there is a reasonable chance the package update itself in ska3 will be easy.  Let's baseline getting this in as a regular update after the holidays.  Otherwise the testing I've done now and my familiarity with everything will be invalidated and we will have to start over 2-3 months from now.

**Comment by taldcroft** [comment]
BTW I have find_attitude running on local server on my laptop and it is lightning fast!  But there is an issue...
