### ISSUE TITLE
Update sherpa to 4.11 on MacOS

### ISSUE THREAD

**Issue by taldcroft** [sot/skare3#239]
On my mac running catalina, I installed sherpa 4.9.1 using `-c $ska3conda` and doing `import sherpa.ui` gave a segfault.  Installing sherpa from the sherpa channel `-c sherpa` gave version 4.11 plus a couple of new libraries, and this worked:
```
The following NEW packages will be INSTALLED:

    libcxx:    4.0.1-hcfea43d_1            
    libcxxabi: 4.0.1-hcfea43d_1            
    sherpa:    4.11.1-py36h0a44026_0 sherpa
```
Not sure about High Sierra, but maybe we should update the tarballs on our channel for Mac?  Shiny branch should maybe update to 4.11 for mac and linux?

**Comment by jeanconn** [comment]
Somewhat speaks to https://github.com/sot/skare3/issues/196 and https://github.com/sot/skare3/issues/225 .

Since you are our prime user, I suppose I need to update one of my test machines to Catalina.

For 'shiny' I was just adding the sherpa channel as you've done and was going to use whatever we got.

**Comment by jeanconn** [comment]
I had this for shiny ; I suppose we can do it for mac sooner but that will be splitting mac and linux versions of sherpa.

**Comment by taldcroft** [comment]
Is there a specific blocker for updating on linux as well?  Since Mac is my primary platform ska3 analysis, I do want sherpa to work sooner than shiny.

**Comment by jeanconn** [comment]
The specific blocker on linux was, IIRC, that Omar built 4.9.1 for us custom on their retired centos5 build systems.

**Comment by jeanconn** [comment]
In this case I don't think I'm being too conservative that it all just breaks on centos5 if build on centos6.  But I think there was a centos5 docker file around to do the build.

**Comment by taldcroft** [comment]
Right, that makes sense, put one more example in the big box of pain that CentOS5 is causing us.  So I have no problem with a different version for MacOS.

**Comment by taldcroft** [comment]
Find_attitude has unit tests which verify the flight-critical sherpa functionality.  I guess that needs to be added to ska_testr.

**Comment by jeanconn** [comment]
Good idea.   https://github.com/sot/ska_testr/issues/17 and I thought I actually had a PR but I guess not.

**Comment by jeanconn** [comment]
Installing on my high sierra system, I got libcxx 9.0.1 and sherpa 4.11.1.  I put those in our core repo to start.  Tom do you want to see if that combination works on catalina?  I still need to do a backup before updatin my system.

**Comment by taldcroft** [comment]
Success on catalina:
```
$ conda create -n ska3-test-sherpa -c $ska3conda -c $ska3conda/core-pkg-repo ska3-flight
$ source activate ska3-test-sherpa
$ conda install -c $ska3conda/core-pkg-repo sherpa
    libcxx: 9.0.1-1               https://icxc.cfa.harvard.edu/aspect/ska3-conda/core-pkg-repo
    sherpa: 4.11.1-py36h0a44026_0 https://icxc.cfa.harvard.edu/aspect/ska3-conda/core-pkg-repo

$ conda install -c $ska3conda/ ska_helpers
$ cd ~/git/find_attitude  # py3-server branch
$ python setup.py test
find_attitude/tests/test_find_attitude.py ......
```
PASS

**Comment by jeanconn** [comment]
Thanks!  I'll rebuild ska3-core with these for OSX then and we should be good.
