### ISSUE TITLE
Use setuptools_scm to set package versions

### ISSUE THREAD

**Issue by javierggt** [sot/skare3#240]
I am opening this issue as a switchboard for all issues related to the implementation of setuptools_scm within skare3 packages. This description will change to include lots of information.

The implementation is based on the ska_helpers package: sot/ska_helpers/pull/1

**All PRs for current ska3-flight packages**

- [x] [Chandra.Maneuver](https://github.com/sot/Chandra.Maneuver/pull/15)
- [x] [Chandra.Time](https://github.com/sot/Chandra.Time/pull/36)
- [x] [Chandra.cmd_states](https://github.com/sot/cmd_states/pull/47)
- [x] [Quaternion](https://github.com/sot/Quaternion/pull/22)
- [x] [Ska.DBI](https://github.com/sot/Ska.DBI/pull/13)
- [x] [Ska.File](https://github.com/sot/Ska.File/pull/6)
- [x] [Ska.Matplotlib](https://github.com/sot/Ska.Matplotlib/pull/10)
- [x] [Ska.Numpy](https://github.com/sot/Ska.Numpy/pull/3)
- [x] [Ska.ParseCM](https://github.com/sot/Ska.ParseCM/pull/4)
- [x] [Ska.Shell](https://github.com/sot/Ska.Shell/pull/14)
- [x] [Ska.Sun](https://github.com/sot/Ska.Sun/pull/7)
- [x] [Ska.arc5gl](https://github.com/sot/Ska.arc5gl/pull/5)
- [x] [Ska.astro](https://github.com/sot/Ska.astro/pull/5)
- [x] [Ska.ftp](https://github.com/sot/Ska.ftp/pull/17)
- [x] [Ska.quatutil](https://github.com/sot/Ska.quatutil/pull/6)
- [x] [Ska.tdb](https://github.com/sot/Ska.tdb/pull/9)
- [x] [acdc](https://github.com/sot/acdc/pull/44)
- [x] [acis_taco](https://github.com/sot/acis_taco/pull/14)
- [x] [agasc](https://github.com/sot/agasc/pull/39)
- [x] [annie](https://github.com/sot/annie/pull/95)
- [x] [chandra_aca](https://github.com/sot/chandra_aca/pull/87)
- [x] [cxotime](https://github.com/sot/cxotime/pull/3)
- [x] [eng_archive](https://github.com/sot/eng_archive/pull/187)
- [x] [hopper](https://github.com/sot/hopper/pull/16)
- [x] [kadi](https://github.com/sot/kadi/pull/150)
- [x] [maude](https://github.com/sot/maude/pull/19)
- [x] [mica](https://github.com/sot/mica/pull/211)
- [x] [parse_cm](https://github.com/sot/parse_cm/pull/19)
- [x] [proseco](https://github.com/sot/proseco/pull/314)
- [x] [pyyaks](https://github.com/sot/pyyaks/pull/9)
- [x] [ska_path](https://github.com/sot/ska_path/pull/5)
- [x] [ska_sync](https://github.com/sot/ska_sync/pull/14)
- [x] [sparkles](https://github.com/sot/sparkles/pull/131)
- [x] [starcheck](https://github.com/sot/starcheck/pull/338)
- [x] [tables3_api](https://github.com/sot/tables3_api/pull/3)
- [x] [testr](https://github.com/sot/testr/pull/19)
- [x] [xija](https://github.com/sot/xija/pull/71)

**Testing**

Testing was done by running testr SKA3_HEAD tests. For the purpose of testing, I created a conda environment which can reproduced in this way:
```
miniconda_install_prefix=/proj/sot/ska/jgonzalez/miniconda3-test
curl -O https://repo.continuum.io/miniconda/Miniconda3-4.3.21-Linux-x86_64.sh
bash Miniconda3-4.3.21-Linux-x86_64.sh -b -p $miniconda_install_prefix
export PATH=${miniconda_install_prefix}:$PATH
conda install python=3.6.2 conda=4.3.21
conda env create -f /proj/sot/ska/jgonzalez/scm_test_env.yaml
```
Issues:
- setuptools_scm needs to be upgraded. It is currently in /proj/sot/ska/jgonzalez/other_packages

**Some History**

This was proposed for engarchive (sot/eng_archive/pull/157), sparkles (sot/sparkles/pull/107) and also discused here (#118 and #52)

**Comment by jeanconn** [comment]
Can close this when Quaternion 3.5.0 is installed.
