### ISSUE TITLE
Update watch_cron_logs to 4.2

### ISSUE THREAD

**Issue by taldcroft** [sot/skare3#253]
https://github.com/sot/watch_cron_logs/pull/6 : Modernize watch_cron_logs

**Comment by jeanconn** [comment]
Regarding task_schedule and watch_cron logs, they are currently installed in production ska usin the ska3-perl metapackage.  It is explicit about just installing them on linux.  

Do you need them installed by default with the ska3-perl packae on osx or if you need them will you just install the conda packages manually?

**Comment by taldcroft** [comment]
Is there now any reason these should be considered `[linux]` only?  I would have them install along with ska3-perl on all platforms.  Basically unless there is a reason why some package doesn't/can't work, then install it.

**Comment by jeanconn** [comment]
That's fine.  I had mostly been thinking that the osx machines are mostly laptops and cron tasks are not that interesting for them, but if you think it has value that's fine.  It will still remain in the separate ska3-perl and not ska3-flight to avoid pulling in all the perl cruft to do most analysis etc.
