### ISSUE TITLE
Chandra.Time won't conda build in master

### ISSUE THREAD

**Issue by jeanconn** [sot/skare3#255]
```
aca-presto% python ska_builder.py --build-root /export/aca/test-django/ Chandra.Time                       - Building package Chandra.Time.
  - Cloning or updating source source Chandra.Time.
  - Updated repo in /export/aca/test-django/src/Chandra.Time
  - Auto-checked out at 3.20.4 which is also tip of master
Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    from Cython.Build import cythonize
ModuleNotFoundError: No module named 'Cython'
  - SKA_PKG_VERSION=
```

Looks like I need maybe need cython in the builder environment to make this work?

**Comment by jeanconn** [comment]
I think this will just be closed by

https://github.com/sot/skare3/pull/254/commits/84d78507767228f7b1ba53fc84209ae31577072d

**Comment by jeanconn** [comment]
@javierggt  Do you understand this?  I think the part that confused me was that Chandra.Time still has cython in the "build" dependencies in the recipe, but I think the code in ska_builder.py now that sets up SKA_PKG_VERSION needs to run setup.py first to do so before anything is passed to the conda build process.  Am I understanding that correctly?  So now that determining the version happens in the ska3_builder environment (and not the conda "build" environment) we need cython in the ska3_builder environment.

cc @taldcroft

**Comment by jeanconn** [comment]
Need to make a new version of ska3_builder to close this out.

**Comment by taldcroft** [comment]
Haven't tried, but I expect we could fix this by:
```
try:
    from Cython.Build import cythonize
except ImportError:
    cythonize = lambda arg: None
```
Then `python setup.py --version` should work without Cython.

**Comment by jeanconn** [comment]
Good idea.  I was thinking the same (that it shouldn't need Cython to get version) but I'm OK with this setup.py fix not getting in to 2020.1, depending on our schedule.  We should probably clean this up and decide if we also update install_requires in Chandra.Maneuver 

https://github.com/sot/Chandra.Maneuver/blob/9f54daafa8c3ceaa69b03912b597b47e784f6e53/setup.py#L16

**Comment by taldcroft** [comment]
What were you thinking of for the update to `install_requires`?  Note that Cython is a build dependency but `install_requires` is about runtime dependencies (from my understanding).

**Comment by jeanconn** [comment]
I was mostly thinking about these set of "small changes to individual package setup.py pieces that would make sense in our current build system".
