### ISSUE TITLE
Versioning policy

### ISSUE THREAD

**Issue by taldcroft** [sot/skare3#256]
About whether to always include the bugfix version even for a new feature-release...

There does not seem to be consensus among big packages, and some leave off the trailing `.0` e.g. astropy 4.0 not astropy 4.0.0, but then there is numpy 1.18.0.

About changing our policy because of SCM, it seems like always including the bugfix .0 can lead to wrong versions just as often as not.  Basically, if a package has the last tag as 1.2.0, we do not know if the next release will be 1.2.1 or 1.3.0 until all the PRs for the next release are in.  If only bug fixes, then 1.2.1, but if there is any new feature it will be 1.3.0 and the scm version of 1.2.1-dev.xxxx will be wrong.

I guess we can have a policy of tagging for a feature release as soon as a feature PR is merged.  So in the example we would tag as 1.3.0-dev.  Then I *think* that scm version will stick with 1.3.0-dev.xxxx.

One thing we do differently from just about everyone else is not include the `v` in front.  I don't know exactly why that is useful, but everyone does it.

**Comment by javierggt** [comment]
> if a package has the last tag as 1.2.0, we do not know if the next release will be 1.2.1 or 1.3.0 until all the PRs for the next release are in. If only bug fixes, then 1.2.1, but if there is any new feature it will be 1.3.0 and the scm version of 1.2.1-dev.xxxx will be wrong.

At least it is consistent in that the version numbers are increasing, which is a requirement. You would get
- 1.2.0
- 1.2.1-dev...
- 1.3.0

If you do not have the bug/patch number and you add it, you will end up with a version sequence that looks like this:
- 1.2
- 1.3-dev...
- 1.2.1

It is about consistency within a package. We could perfectly decide not to have a patch version, but then we should stick with it. For reference, check what they say about it: https://github.com/pypa/setuptools_scm/#semantic-versioning-semver

**Comment by javierggt** [comment]
ah, and I do not think we should force ourselves to tag a release on every merge.

**Comment by taldcroft** [comment]
Ah, now I see your point about why it matters, namely if we have auto-built packages that go into a package repo then having them sort properly makes a difference. I was just thinking about personal development work where ordering is not an issue, I just need a uniquely identifiable version.

OK, looks like a new policy (starting after the 2020.1 release).

**Comment by taldcroft** [comment]
And I was not suggesting tagging on every merge.  For perfection if we want the auto-built versions to be meaningful we can choose to create dev tags when there is a feature update (which can only happen once per release).  In practice probably not worth the bother!

**Comment by taldcroft** [comment]
By "meaningful", I mean that a conda package which is a pre-release version of 1.3.0 would be versioned as 1.3.0-dev... not 1.2.2-dev.  But like I said, likely not worth the bother for us.

**Comment by javierggt** [comment]
Yes, I understand. Personally,I do not mind that the dev version does not match the actual resulting version.

**Comment by jeanconn** [comment]
Regarding "starting after the 2020.1 release", if we have another week, I'm fine to re-version any packages with x.x versions in the 2020.1 release that are already in here, and I assume Javier will cut x.x.x releases on the rest of the packages.  So we could just do this now.

**Comment by taldcroft** [comment]
Works for me!

**Comment by jeanconn** [comment]
I note as an aside, that Javier and I came across what could be considered a setuptools_scm bug; if more than one github release is tagged at the same sha, the first release tag may be used for the build instead of the most recent.  So to "re-version" the x.x projects already tagged in this release I can either make no-op commits or delete the last release tags.  I was planning to just delete the release tags.  I don't think we care but wanted it out there.

**Comment by jeanconn** [comment]
And are we moving to `vx.x.x` or no `x.x.x`?

**Comment by taldcroft** [comment]
I don't think this is a bug, as I would consider the behavior for two tags at the same commit to be undefined.  As in, I don't think time is a relevant metric for ordering tags, rather it should be position along the relevant branch.  If I make a tag today that is on a commit back in history, that does not take precedence over the one closest to HEAD.

But as you said, not a big deal and we just don't double-tag commits.

**Comment by taldcroft** [comment]
Sticking with `x.x.x` unless someone can think of a reason why `vx.x.x` is better.

**Comment by javierggt** [comment]
I think it is a bug, because setuptools_scm should be able to parse both version strings and take the latest.

**Comment by javierggt** [comment]
I think this discussion is concluded.
