### ISSUE TITLE
Post 2020.1 actions

### ISSUE THREAD

**Issue by taldcroft** [sot/skare3#288]
- [x] Update ska_sync_data on chimchim and cheru to get events3.db3 (updated `/proj/sot/ska3/flight/ska_sync_files`).
- [x] Update kadi events and commands updates to run on Python 3 in flight ska3.
  - Right now `events3.db3` is being updated via the job on kadi:/export/tom/...
  - Will wait until Monday to change cron jobs.

**Comment by jeanconn** [comment]
I also heart-attacked arc so I could be sure it was running the updated task_schedule.pl / watch_cron_logs.pl .
