### ISSUE TITLE
Make sure namespace packages are native

### ISSUE THREAD

**Issue by javierggt** [sot/skare3#290]
Native namespace packages is the preferred way since python 3.3. The only required change is to remove the `__init__.py` files.

The following packages include non-native namespace packages:
- Chandra.Maneuver
- Chandra.Time
- Ska.DBI
- Ska.File
- Ska.Matplotlib
- Ska.Numpy
- Ska.ParseCM
- Ska.Shell
- Ska.Sun
- Ska.arc5gl
- Ska.astro
- Ska.ftp
- Ska.quatutil
- Ska.tdb
- cmd_states
- eng_archive

**Comment by javierggt** [comment]
@taldcroft and @jeanconn,

I propose that one of you approves one of the PRs, let's say sot/ChandraManeuver (they are all identical), and then I merge all.

**Comment by javierggt** [comment]
NOTE: conda recipes need to be changed.

**Comment by jeanconn** [comment]
And I've forgotten, what needs to change in the recipes?

**Comment by taldcroft** [comment]
The bit where they get installed as eggs, IIRC.

**Comment by jeanconn** [comment]
Ah.  As somebody who has not actually worked with the implicit namespace packages I was confused on that point.  I thought the packaging was independent of the egg/no-egg issue.

**Comment by taldcroft** [comment]
It will still work and install (I believe) as an egg install, but we lose all the benefit.  I.e. the possible fix for remote access using cheta bug.  And not having all that crap in sys.path.

**Comment by jeanconn** [comment]
OK.  So wrt @javierggt 's "conda recipes need to be changed" comment above, the conda recipes probably don't *need* to be changed for the implicit/native namespace changes but it seems a good idea to just do it at once.  Would we also change them all to "python setup.py" etc or just wait for shiny for those updates?

**Comment by javierggt** [comment]
argh, I have to remember... conda recipes might have to be changed so package versions are properly determined.

**Comment by jeanconn** [comment]
Would that be a recipe update or a change to ska_builder.py or ska_helpers?  All good.

**Comment by javierggt** [comment]
That would be changing build.sh to remove the --egg option.

**Comment by taldcroft** [comment]
I don't have a strong technical justification between pip and python setup.py, but if no strong discriminator turns up then I would prefer the python setup.py version:
```
script: python setup.py install --single-version-externally-managed --record=record.txt
```

**Comment by taldcroft** [comment]
And I very much *want* to make the change unless there is a good reason not to.

**Comment by jeanconn** [comment]
I was just wondering if the python setup.py install would just make more work to merge changes with the shiny branch.  But fine either way.

**Comment by taldcroft** [comment]
It may be a mess no matter what, but we'll figure it out.

**Comment by jeanconn** [comment]
:+1:

**Comment by taldcroft** [comment]
All the referenced PRs are now merged!  :rocket: :tada:

**Comment by taldcroft** [comment]
As noted above, the recipes need to change in order for the packages to actually be installed as native namespace packages and not be hidden inside eggs.  I have done the recipe changes now in `shiny` and this exposed a new issue related to the way that pytest does test discovery. For a native namespace package it doesn't understand that, e.g. `Maneuver` is a sub-package of `Chandra`, so it ends up collecting tests within this as an independent `Maneuver` package, which turns `__package__` to be `Maneuver`.  We may have discussed this before but if so I have/had forgotten.

In any case, after a fair bit of thrashing to figure this out (since it was buried in a weird interaction of ska_helpers and pytest, not so easy for me), I finally came to the conclusion that the only resolution is to hard-code the package name in the call to `get_version` within namespace package `__init__.py` files. I was unable to find anything else that worked despite some trying. The result is the slew of PR's I put in this evening. I believe these are all compatible with ska3-flight but this needs some independent testing.

An example of the problem is below:
```
(ska3) ➜  cmd_states git:(master) conda activate ska3-shiny
(ska3-shiny) ➜  cmd_states git:(master) python setup.py test     
running test
WARNING: Testing via this command is deprecated and will be removed in a future version. Users looking for a generic test entry point independent of test runner are encouraged to use tox.
running egg_info
writing Chandra.cmd_states.egg-info/PKG-INFO
writing dependency_links to Chandra.cmd_states.egg-info/dependency_links.txt
writing top-level names to Chandra.cmd_states.egg-info/top_level.txt
package init file 'Chandra/__init__.py' not found (or not a regular file)
writing manifest file 'Chandra.cmd_states.egg-info/SOURCES.txt'
running build_ext
================================================ test session starts ================================================
platform darwin -- Python 3.6.10, pytest-5.4.2, py-1.8.1, pluggy-0.13.1
rootdir: /Users/aldcroft/git/cmd_states
collected 4 items                                                                                                   

Chandra/cmd_states/tests/test_get_cmd_states.py ...s                                                          [100%]

================================================= warnings summary ==================================================
/Users/aldcroft/miniconda3/envs/ska3-shiny/lib/python3.6/site-packages/setuptools_scm/__init__.py:63
/Users/aldcroft/miniconda3/envs/ska3-shiny/lib/python3.6/site-packages/setuptools_scm/__init__.py:63
  /Users/aldcroft/miniconda3/envs/ska3-shiny/lib/python3.6/site-packages/setuptools_scm/__init__.py:63: PendingDeprecationWarning: parse functions are required to provide a named argument 'config' in the future.
    version = _call_entrypoint_fn(root, config, ep.load())

/Users/aldcroft/miniconda3/envs/ska3-shiny/lib/python3.6/site-packages/ska_helpers/version.py:89
  /Users/aldcroft/miniconda3/envs/ska3-shiny/lib/python3.6/site-packages/ska_helpers/version.py:89: UserWarning: Traceback (most recent call last):
    File "/Users/aldcroft/miniconda3/envs/ska3-shiny/lib/python3.6/site-packages/ska_helpers/version.py", line 41, in get_version
      dist_info = get_distribution(distribution or package)
    File "/Users/aldcroft/miniconda3/envs/ska3-shiny/lib/python3.6/site-packages/pkg_resources/__init__.py", line 482, in get_distribution
      dist = get_provider(dist)
    File "/Users/aldcroft/miniconda3/envs/ska3-shiny/lib/python3.6/site-packages/pkg_resources/__init__.py", line 358, in get_provider
      return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
    File "/Users/aldcroft/miniconda3/envs/ska3-shiny/lib/python3.6/site-packages/pkg_resources/__init__.py", line 901, in require
      needed = self.resolve(parse_requirements(requirements))
    File "/Users/aldcroft/miniconda3/envs/ska3-shiny/lib/python3.6/site-packages/pkg_resources/__init__.py", line 787, in resolve
      raise DistributionNotFound(req, requirers)
  pkg_resources.DistributionNotFound: The 'cmd_states' distribution was not found and is required by the application
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/Users/aldcroft/miniconda3/envs/ska3-shiny/lib/python3.6/site-packages/ska_helpers/version.py", line 78, in get_version
      version = get_version(root=Path(*roots), relative_to=module.__file__)
    File "/Users/aldcroft/miniconda3/envs/ska3-shiny/lib/python3.6/site-packages/setuptools_scm/__init__.py", line 143, in get_version
      return _get_version(config)
    File "/Users/aldcroft/miniconda3/envs/ska3-shiny/lib/python3.6/site-packages/setuptools_scm/__init__.py", line 147, in _get_version
      parsed_version = _do_parse(config)
    File "/Users/aldcroft/miniconda3/envs/ska3-shiny/lib/python3.6/site-packages/setuptools_scm/__init__.py", line 118, in _do_parse
      "use git+https://github.com/user/proj.git#egg=proj" % config.absolute_root
  LookupError: setuptools-scm was unable to detect version for '/Users/aldcroft/git/cmd_states/Chandra'.
  
  Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.
  
  For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
  
  
  
    warnings.warn(traceback.format_exc() + '\n\n')

/Users/aldcroft/miniconda3/envs/ska3-shiny/lib/python3.6/site-packages/ska_helpers/version.py:90
  /Users/aldcroft/miniconda3/envs/ska3-shiny/lib/python3.6/site-packages/ska_helpers/version.py:90: UserWarning: Failed to find a package version, setting to 0.0.0
    warnings.warn('Failed to find a package version, setting to 0.0.0')

Chandra/cmd_states/tests/test_get_cmd_states.py::test_get_states_main
  /Users/aldcroft/miniconda3/envs/ska3-shiny/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
    return f(*args, **kwds)

-- Docs: https://docs.pytest.org/en/latest/warnings.html
===================================== 3 passed, 1 skipped, 5 warnings in 1.49s ======================================
```

**Comment by javierggt** [comment]
but why have the tests worked so far? because I made the changes to the recipes in order to build the last release with namespace packages,  and tests passed.

While doing that, we saw the warning about Maneuver not being found when pytest was trying to find the module. It then went to the higher directory (Chandra) and was able to import. Same with all the other packages. So where does the difference in behavior come from?

**Comment by javierggt** [comment]
I am guessing that you have the older version of ska_helpers, which fixed this warning.

**Comment by javierggt** [comment]
Ah, I see. That was because the test was not within testr, and the hack in PR#10 works only within testr. If you have any suggestion... I think pytest should not be doing what is doing. That's what I think.

**Comment by javierggt** [comment]
This was implemented for shiny.
