### ISSUE TITLE
ska_builder environment needs minimum dependencies for all setup.py to run

### ISSUE THREAD

**Issue by taldcroft** [sot/skare3#292]
`Ska.Numpy` showed a problem related to the SCM changes, namely that my initial environment for running ska_builder.py was minimal (just Python 3.8 + gitpython) and running `setup.py` failed because of imports for Cython and numpy.  In the current scheme that just means tossing those two packages into the builder environment as well.

**Comment by taldcroft** [comment]
In addition `backstop_history` requires `ska_helpers` by importing a version that is not actually used.

**Comment by jeanconn** [comment]
I figured the minimal ska_builder running environment would still be installed via the ska3build metapackage.

**Comment by jzuhone** [comment]
@taldcroft i’ll be removing those version imports from that package and the other ACIS ones.

**Comment by taldcroft** [comment]
@jzuhone - thanks!

@jeanconn - indeed the current version of ska3_builder doesn't have all that is needed, but more critically it has a number of pinned conda packages which really doesn't fly for the shiny work I'm doing now.  

The point for our package development is that every package setup.py should be able to run `python setup.py --version` with no dependencies except setuptools and setuptools_scm.  So e.g. `Ska.Numpy` should put the Cython and numpy dependent stuff into a try/except and at least not crash without them.  If you try to actually build without them then of course things go south.

**Comment by jeanconn** [comment]
Indeed, so I'm not sure if this issue should be in Ska.Numpy as a "go fix those Cython import" or if you are saying with this issue that the ska3_builder package  should be updated or retired as no-longer-needed.
