### ISSUE TITLE
Make a pull request template in every Ska3 project repo

### ISSUE THREAD

**Issue by taldcroft** [sot/skare3#293]
See: https://help.github.com/en/github/building-a-strong-community/creating-a-pull-request-template-for-your-repository

Using the automation features in skare3_tools this should be straightforward, basically adding a file  `.github/pull_request_template.md`.

Could be something like:

## Testing

- [ ] Passes unit tests on MacOS, linux, Windows (at least one required)
- [ ] Functional testing
  - ...

Fixes #

**Comment by taldcroft** [comment]
The motivation here are the occasions when I have forgotten to run unit tests.

**Comment by javierggt** [comment]
I think this is a good idea. I can create a generic template and add it to all ska3 projects. I would need to know what functional tests are done in projects that need functional tests, so the template can be customized. Either that or you guys modify the template for the projects that need functional tests.
