### ISSUE TITLE
Add github actions to ska packages

### ISSUE THREAD

**Issue by javierggt** [sot/skare3#295]
As the title says: we will be adding automated actions to ska packages, and this is the uber-issue.

Changes should include:
- building in CentOS 5 (all packages) and Mac OS (some packages). This will run whenever there is a push to master or a release is created. Resulting conda packages are uploaded to Google drive.
- automatically edit release descriptions to include latest PRs. This is done when a release is created.
- automatically open an issue labeled "Package Update" in sot/skare3. Also when a release is created. This could be when a release is _published_ instead.
- a pull request template (#293)

I will first add Chandra.Time for you to check. Then I will add the rest. The list of packages is:
- [x] Chandra.Maneuver
- [x] Chandra.Time (macos + linux)
- [x] Quaternion
- [x] Ska.DBI
- [x] Ska.File
- [x] Ska.Matplotlib
- [x] Ska.Numpy (macos + linux)
- [x] Ska.ParseCM
- [x] Ska.Shell
- [x] Ska.Sun
- [x] Ska.arc5gl
- [x] Ska.astro
- [x] Ska.ftp
- [x] Ska.quatutil
- [x] Ska.tdb
- [x] acdc
- [x] agasc
- [x] annie
- [x] chandra_aca
- [x] cmd_states
- [x] cxotime
- [x] eng_archive
- [x] hopper
- [x] kadi
- [x] maude
- [x] mica
- [x] parse_cm
- [x] proseco
- [x] pyyaks
- [x] ska_helpers
- [x] ska_path
- [x] ska_sync
- [x] sparkles
- [x] starcheck
- [x] tables3_api
- [x] taco (macos + linux)
- [x] task_schedule (macos + linux)
- [x] testr
- [x] xija  (macos + linux)
- [x] sot/aca_egse
- [x] sot/watch_cron_logs

**NOTE the ones missing in the list above**
ACIS ops:
- [ ] acisops/acis_thermal_check
- [ ] acisops/acisfp_check
- [ ] acisops/backstop_history
- [ ] acisops/dea_check
- [x] acisops/dpa_check
- [ ] acisops/psmc_check

**Comment by javierggt** [comment]
@jeanconn, would you mind merging the PRs for a couple of packages you intend to release today? (if any). Quaternion, for example.

**Comment by jeanconn** [comment]
Per our conversation, none of these are going today, but Quaternion will probably go next week if we want to start with that as a dog fooding test case.

**Comment by javierggt** [comment]
I am about to add github actions to acis packages. @jzuhone do you also want the PR template Tom requested? (#293)

**Comment by jzuhone** [comment]
@javierggt yes, that'd be great

**Comment by javierggt** [comment]
there is also an action that edits the release notes to mention all merges since last release. That one works in test repositories, but I do not know if it works fine everywhere.

**Comment by jeanconn** [comment]
Since we can still edit the release notes, I think it is benign if it isn't perfect yet.

**Comment by javierggt** [comment]
@jzuhone I can't push a branch to the repositories.

**Comment by jeanconn** [comment]
They generally do PRs from their own forks which I think you could do too in this case @javierggt ?

**Comment by jzuhone** [comment]
@javierggt which repo did you try?

**Comment by jzuhone** [comment]
@javierggt try now.

**Comment by javierggt** [comment]
I just noticed that sot/find_attitude is not included here. It should be, shouldn't it?

**Comment by jeanconn** [comment]
Yes.  I'm not sure about the best way to check for any other missing ones but assume we'll notice if we just have missing automatic builds for a dependency.

**Comment by javierggt** [comment]
I noticed by creating a ska3-dev environment including this channel: https://cxc.cfa.harvard.edu/mta/ASPECT/ska3-conda/dev

The only ska3-dev package not coming from this channel was find_attitude.
