### ISSUE TITLE
kadi package provides Chandra.Time

### ISSUE THREAD

**Issue by taldcroft** [sot/skare3#3]
Looks like a copy-paste oops in `meta.yaml`.
```
(ska3) neptune$ tar tvf kadi-3.20.1-py36_0.tar.bz2 
...
-rw-rw-r--  0 jzuhone staff       1 May 22 14:37 lib/python3.6/site-packages/Chandra.Time-3.20.1-py3.6-macosx-10.9-x86_64.egg-info/not-zip-safe
...
```

**Comment by jeanconn** [comment]
Yeah, I'll have to test the builds both by git ssh fetch and https fetch.  This one had the wrong URL at the bottom of the meta.yaml so was a problem for https fetch.

https://github.com/sot/ska-conda/blob/9c2c7cd10cdb117ef6da1021196bd236584bb4ab/ska_conda/pkg_defs/kadi/meta.yaml#L51

**Comment by taldcroft** [comment]
> I'll have to test the builds both by git ssh fetch and https fetch.

I'd be inclined to remove the automated path guessing (currently SSH) and hardwire the recipe to always use the SSH path.  Basically if you are in the business of building Ska packages, SSH is required.  Plan B would be generating a token for this (that gets put in a file with user-access protection), but annoyingly there is no way to generate a token with only read privilege, it has to include full write.
