### ISSUE TITLE
Drop support for CentOS-5 and 32-bit for ska3-matlab 2020-010

### ISSUE THREAD

**Issue by taldcroft** [sot/skare3#310]
The MATLAB tools 2020-010 release with MATLAB 2019b will definitely not support CentOS-5 and 32-bit machines, so concurrent with that release we can drop all support for that configuration in Ska3.

Current plan is to support only CentOS-7+ for MATLAB tools on linux going forward, but there are a few actions needing work before that is firm.

**Comment by jeanconn** [comment]
I think this is a issue for which there was nothing for us to do.

**Comment by taldcroft** [comment]
:tada: 💥
