### ISSUE TITLE
Update acisops/acis_thermal_check to acis_thermal_check version 3.0

### ISSUE THREAD

**Issue by chandra-xray** [sot/skare3#331]
Instead of using pitch from the commanded states to use in the model and
compute the off-nominal roll, calculate the pitch and off-nominal roll using the
target quaternion and the ephemeris. This provides updated pitch and roll more
often in the model and should be equivalent to what @matthewdahmer is doing when
he runs the FOT models. This improves the roll validation on the ACIS thermal
model pages.

Increase the size of all plots to match size of those on the focal plane page.
Reduce duplicated code in calc_model between the different check tools;
allow them to perform additional operations via _calc_model_supp, which they
override.

Move the detector housing heater history file, dahtbon_history.rdb, to the
package instead of copying it around all of the time.

Swap the red and blue colors on validation plots to match FOT scheme.

Plot FEP count on CCD count prediction plot.

Add plots of CCD/FEP count and (optionally) Earth solid angle for validation
runs for diagnostic purposes.

Display the version of the check package used in run.dat, thanks to
ska_helpers.

Print the MD5 sum of the thermal model in run.dat for reproducibility purposes.

Vastly improved testing suite with answers locally stored in the various check tools.

Added a new method for running a prediction-only run.

Includes the following merges:
- PR #25: acis_thermal_check 3.0

**Comment by jzuhone** [comment]
@jeanconn I used the wrong tag for this at first--make sure you pick up the 3.0.0 tag and not the v3.0.0 tag.
