### ISSUE TITLE
Confirm that ska3-core is the minimal set of packages

### ISSUE THREAD

**Issue by taldcroft** [sot/skare3#36]
But consider if current packages might be there for other reasons besides supporting ska3-flight packages?

In general, fixing (adding) back packages seems a reasonable approach if we identify dependencies.

**Comment by jeanconn** [comment]
Maybe right here we can start to capture the list of core packages that we'd like that may or may not  be explicit dependencies of our other packages?
 - ipython
 - nbconvert
 - jupyter
 - qt
 - pyqt
 - sphinx

Others that we've used for analysis that are fine to keep as bonus items
  - pandas
  - networkx
  - scikit-learn
  - line_profiler
  - pillow
  - spyder

Things I'm not sure we've used but maybe could be useful?
 - sqlalchemy

Jean would like to add
  - astroquery

**Comment by taldcroft** [comment]
I haven't used sqlalchemy in a long while and probably won't.   Out of your list that is the only one I would vote to remove.  And of course adding astroquery is great.  BTW networkx is used in find_attitude, so that is a core dependency.

**Comment by jeanconn** [comment]
I just updated my comment when I saw that sqlalchemy appears in kadi tests so should probably be in the kadi dependencies.

find_attitude doesn't run in Py3 so isn't in here at all.

**Comment by taldcroft** [comment]
About kadi, do you mean the top-level `sqlalchemy` directory?  That is orphaned code from my first idea for kadi before settling on django.  I should just remove that.

https://github.com/sot/kadi/search?q=sqlalchemy&unscoped_q=sqlalchemy

**Comment by jeanconn** [comment]
Yes, OK. If those test files aren't needed at all, I'll plan to remove sqlalchemy from the explicit list (will see if it gets installed as somebody else's dependence, but doesn't look like it from grepping around the the conda pkg dependencies).

**Comment by taldcroft** [comment]
Done: https://github.com/sot/kadi/pull/115

**Comment by jeanconn** [comment]
I've started to capture this in an updated ska3-dev metapackages that just has what I think we *want* in the environment.  The idea would be that you'd install ska3-dev while letting if float and then use the list of packages from defaults to make a new ska3-core list.

#33 [commit with new ska3-dev](05345356ed25a8a576e8b827dedd8f093c1311d3)

**Comment by taldcroft** [comment]
IPython uses zeromq for IPC (https://ipython.org/ipython-doc/3/parallel/parallel_intro.html#security).  I'm surprised this is not a dependence already.

**Comment by taldcroft** [comment]
find_attitude?

**Comment by jeanconn** [comment]
OK, so I still thought find_attitude was Py2 only which was why it is commented out in the py3 skare branch.

**Comment by taldcroft** [comment]
We can skip mpld3 for now.  It looks like there may be a new maintainer coming on board, but maybe mpld3 is not something we should baseline for active plots.  The aimpoint_mon stuff can live without it by just making the static page.

**Comment by taldcroft** [comment]
About find_attitude, yes, and now I remember you said that at least once before.  That will have to come later.  There shouldn't be any particular problem making it work on Py3 (hopefully!).

**Comment by jeanconn** [comment]
WRT zeromq, on OSX it looks like I'm getting `pyzmq` from dependencies but not `zeromq`.  Not sure about the best way to test IPython.

**Comment by jeanconn** [comment]
With regard to earlier comments in the thread, looks like astroquery isn't in the `defaults` channel for now so that can wait.

**Comment by taldcroft** [comment]
For testing you can try Jupyter notebook.  If that works then I think all is good.

**Comment by jeanconn** [comment]
I had, in fact, popped jupyter notebook up, but I wasn't sure how many paces to run through before deciding it was fine, or if I needed to run some test suite.  Either way, I've added zeromq to the ska3-core build and will retest the new environment with regard to ska packages working and jupyter notebook working.
