### ISSUE TITLE
Do we still need ska3_flight_build_order.txt?

### ISSUE THREAD

**Issue by javierggt** [sot/skare3#385]
ska3_flight_build_order.txt is kind of a hack. This should be specified by the config files. Lately we have removed most internal build dependencies. Is it still needed?

**Comment by jeanconn** [comment]
How is it specified by config files?

**Comment by taldcroft** [comment]
The order is not relevant any more, but it does provide the list of packages to build.  I'm not sure where else that exists.

**Comment by jeanconn** [comment]
For me, I sometimes actually ran the package build tests made only of the environment built locally, which required the order for "bootstrapping".  Probably don't care but not sure what throwing the order away buys us?  If by config files you mean by the package meta.yaml files, the builder could use them to "solve" for build order if correct but we have some circular dependencies.

**Comment by javierggt** [comment]
> If by config files you mean by the package meta.yaml files, the builder could use them to "solve" for build order if correct but we have some circular dependencies.

that is what I meant. Do you know where the circular dependencies are?

Lately I never build all packages, so that is why I did not see the reason for having the list. So the list does not include all packages in the pkg_defs directory?

**Comment by jeanconn** [comment]
IIRC, chandra_aca and mica are circular, but I set mica as just a test dependence of chandra_aca so it wasn't a hard conflict.  It is somewhat expected that that packages that we use all-over-the-place also call each other.

**Comment by taldcroft** [comment]
Agreed with @jeanconn, I'm sure there are other circular runtime dependencies, e.g. involving kadi and cheta and xija.

I do build all packages rather frequently. Currently in shiny there are 53 packages in `ska3_flight_build_order.txt` and 63 packages in `pkg_defs`:
```
(ska3) ➜  skare3 git:(shiny) ✗ diff pkgs_defs_list build_order_sorted
18,19d17
< aca_egse
< aca_view
27d24
< bep_pcb_check
31d27
< django
33,34d28
< fep1_actel_check
< fep1_mong_check
37d30
< jplephem
54d46
< ska3_builder
60d51
< task_schedule
62d52
< watch_cron_logs
```

**Comment by javierggt** [comment]
ok, understood. Closing.
