### ISSUE TITLE
Unique tag in ska_version

### ISSUE THREAD

**Issue by taldcroft** [sot/skare3#39]
(I thought of this a while back but forgot to mention it).

In addition to the ska3-* package versions, there should also be some kind of tag in the version output that reflects the collective versions of all packages.  For instance the first 7 digits of the md5 hash of the output of `conda list` (or something derived from the JSON components).

The point is that a test environment may have all the same ska3-* packages but one or more custom-installed packages.  This should show up in ska_testr.

**Comment by jeanconn** [comment]
This is of course something I'd like but figured you'd hate.

**Comment by jeanconn** [comment]
For this, for the conda packages do you want to be sensitive to the build version or just the package version (the thing we are explicitly controlling).

**Comment by taldcroft** [comment]
I think just package version is sufficient.

**Comment by jeanconn** [comment]
If we don't care, it is probably easier to use the build versions too.

The json that I'm fetching now with "conda list --json" is great to reformat for the ska3- pieces, but it doesn't have any pip installed packages.  I'm assuming you want visibility on those?

If so, we need to use something else to get a list that includes pip installed packages, either another call to "conda list" or something else.  And if we just have the string out of "conda list" it has those build versions in the text that you'd be using to make the new hash, unless you want to parse the conda list output.

**Comment by taldcroft** [comment]
That's annoying, seems like a bug (that pip packages are not included).  Just do anything for now, doesn't have to be a perfect solution.  E.g. md5 hash of the string output of `conda list`.

**Comment by jeanconn** [comment]
Gotcha.  And yeah, I wasn't shooting for perfection but also figured that the current string out of ska_version is fine for the first round of testing (that things sort of work).

**Comment by jeanconn** [comment]
Closed by #48
