### ISSUE TITLE
Support data syncing by adding ska_sync 0.1.1 or similar

### ISSUE THREAD

**Issue by taldcroft** [sot/skare3#51]
Not an immediate priority, but the data syncing provided by ska_sync should be included.  The [syncing process defined in the docs](https://github.com/sot/skare3/wiki/Ska3-runtime-environment-for-users#syncing-data-to-be-revised) seems a little kludgey but not sure if there is a better way.

**Comment by jeanconn** [comment]
Are there any open actions for skare3 for this issue?
