### ISSUE TITLE
Add package sphinx-argparse to ska3-core

### ISSUE THREAD

**Issue by javierggt** [sot/skare3#513]
sphinx-argparse is a good package to have. It generates the documentation shown [here](https://sot.github.io/skare3_tools/scripts.html)
These are the packages that would be added for this:
- sphinx-argparse-0.2
- commonmark-0.9.1
- future-0.18.2

**Comment by jeanconn** [comment]
To keep reproducible, should probably get added to ska3-core-latest too.

**Comment by javierggt** [comment]
right, I think the actual procedure should be to first add it to ska3-core-latest, and then let ska3-core be whatever the combine_arch script gives.

**Comment by javierggt** [comment]
I would add just sphinx-argparse to ska3-core, without version, and the other two would be pulled in.

**Comment by jeanconn** [comment]
Not sure about adding anything without version to ska3-core, but yeah, for new OTS or ska packages, seems like the "latest" packages is the place to add them first and then do the whole rebuild process.  

It also doesn't apply here but seems like an explicit version (or pattern) can be defined in ska3-core-latest if needed but we might need a comment somewhere to support/explain any restrictions like that.

**Comment by javierggt** [comment]
oops, sorry, I just noticed that in the last comment I intended to say

> I would add just sphinx-argparse to **ska3-core-latest**, without version, and the other two would be pulled in.

so we agree, I believe.

I added these packages to the shiny conda channel.
