### ISSUE TITLE
post-shiny docs update

### ISSUE THREAD

**Issue by javierggt** [sot/skare3#554]
In this issue I want to collect all items you think should be done to documentation. This is similar to older issues that I just closed because they are out of context.

Perhaps these things need to be documented?
- [ ] package building/workflows
- [ ] conda channels (masters, test, flight)
- [x] best practices for ipython startup file setup? (from an old issue)

Perhaps these need to be updated?
- [ ] this page: https://occweb.cfa.harvard.edu/twiki/bin/view/Aspect/SkaPython3. 

What else?

**Comment by jeanconn** [comment]
OBE
