### ISSUE TITLE
Add package sot/jobwatch 0.2.0

### ISSUE THREAD

**Issue by javierggt** [sot/skare3#568]
Add package jobwatch 0.2.0

**Comment by jeanconn** [comment]
I'm leaning toward deferring on this one.

**Comment by javierggt** [comment]
ok, will remove from milestone then.

**Comment by javierggt** [comment]
I just noticed this issue is not only to add the package to ska3-flight, but to add the package to pkg_defs...

**Comment by jeanconn** [comment]
Sorry.  I guess I just had the recipe in my local branch for testing but hadn't pushed it.

**Comment by jeanconn** [comment]
So not sure if you want to merge and rebase or cherry pick or...

**Comment by jeanconn** [comment]
Also, there's now a jobwatch 0.2.0.

**Comment by jeanconn** [comment]
Sorry about the work and rework on this one!  And I suppose I need to add more of the github workflows to jobwatch.

**Comment by javierggt** [comment]
right, but I can build this version.
