### ISSUE TITLE
reduce circular dependencies

### ISSUE THREAD

**Issue by jeanconn** [sot/skare3#6]
Right now, we've got somewhat circular dependencies for testing 

kadi <=> chandra.cmd_states
mica <=> chandra_aca

Not sure if there might be a reasonable way to reduce those dependencies to make it easier to build and test packages as we go.  With the circular dependencies, one needs to build without testing, build the other package with testing, and then go back and test the first package... if you want a tested package.

**Comment by jeanconn** [comment]
I think build tests are still fine as an optional item.

So what is our focus for the "something" that you'd like to work to start?  An environment that has some subset of the modules (tbd) and passes ska_testr tests on some machine (tbd)?  Run with or without a /proj/sot/ska/data with some subset of test data (tbd)?

**Comment by jeanconn** [comment]
And yes, I opened this issue as a "bonus for future" work type thing... nothing that is blocking progress now.

**Comment by taldcroft** [comment]
If we can get to passing ska_testr (not including tests like Ska.engarchive long regress) on HEAD linux (with all resources available) that would be an awesome launch point.

**Comment by jeanconn** [comment]
OK.  I think I'll have to set up a dev ska independent from the the conda envs I've been using to have something to source into to set SKA and such from ska_envs as you suggest in your wiki.  Hadn't gotten to that integration step.  Most tests are fine except Chandra.cmd_states complains there is no 'SKA'.
