### ISSUE TITLE
Update acisops/dpa_check to Move conftest to use testr

### ISSUE THREAD

**Issue by javierggt** [sot/skare3#623]
Includes the following merges:
- PR [#29](https://github.com/acisops/dpa_check/pull/29): Move conftest so we can use testr

**Comment by jeanconn** [comment]
Not sure why the acis package update issues are coming in without versions...

**Comment by jeanconn** [comment]
Ah; because it looks like "Move conftest to use testr" is what John has named the "release".  Do we have a recommended convention for them?

**Comment by jeanconn** [comment]
Or should the code to make an package update issue just also pull the tag corresponding to the release?

**Comment by javierggt** [comment]
ha, right. That always throws me off too.

I have thought that maybe I could change the skare3_tools script it to say "Update {package} to Release {release tag}" instead of using "Update {package} to {release name}". It should be possible and would not require any convention.

**Comment by jeanconn** [comment]
Yeah, that's what I came around to too.  Seems no fire under that but might be a good idea to make it easier to see we're getting the right versions in when we look at the list of issues.
