### ISSUE TITLE
Docs question

### ISSUE THREAD

**Issue by taldcroft** [sot/skare3#63]
In the user docs, is this needed?
```
% chmod o-rwx ~/.condarc
```

**Comment by jeanconn** [comment]
I don't think so.  I assumed you added it, but wasn't sure if you were motivated by the password we had the the .condarc or if you got some error I didn't.

**Comment by taldcroft** [comment]
Funny, I assumed you had added it, but maybe I cranked it out in an early draft and forgot.  OK, removing.

**Comment by jeanconn** [comment]
I'll be sure to re-test eventually and will add it back if I see anything weird.
