### ISSUE TITLE
Add package nodejs 10.13.0

### ISSUE THREAD

**Issue by taldcroft** [sot/skare3#640]
This allows matplotlib widgets to work with jupyter lab 2.x.
```
  nodejs             10.13.0  h0a44026_0    pkgs/main/osx-64      12 MB
```

**Comment by javierggt** [comment]
I was able to get nodejs 10.13.0 in all three. However:
- I noticed that there by default in windows it would install version 14.8.0
- in linux, it also installed libgcc 7.2.0

**Comment by taldcroft** [comment]
The original comment mentioned `libgcc` for linux, which seemed weird. I see now that you edited this away, so is that no longer coming along for the ride? If so this looks great.

**Comment by javierggt** [comment]
that's right.
