### ISSUE TITLE
Update package jpeg to version 9c

### ISSUE THREAD

**Issue by javierggt** [sot/skare3#651]
We currently have jpeg 9b in ska3-core. When trying to install CIAO 4.13 in a ska3 environment, there is a conflict involving jpeg 9b. This conflict is resolved if one installs version 9c instead. This is not the latest jpeg library, but it is a simple change that allows the installation. Perhaps 9d works too?

**Comment by jeanconn** [comment]
Sounds reasonable, though I assume this would still need to be tested with a ska3 with the perl stuff too (not that we care that much, I'm just guessing it wasn't in the test environment you were using to resolve these dependency issues).

**Comment by javierggt** [comment]
ok, good to know. I will try that as well.

Is there any functional test one should do as well?

**Comment by jeanconn** [comment]
Since we haven't completely moved to aca_view, I'd probably run test splat, but if there is a conflict we could just stick with using an old ska3 for the aca egse until aca_view is more approved for realtime.

**Comment by javierggt** [comment]
I don't know what is meant by `test splat` or what to look for. What I can say is that the following succeds in installing:
```
conda create -n ciao-ska-test
conda activate ciao-ska-test
conda install --override-channels -c https://icxc.cfa.harvard.edu/aspect/ska3-conda/flight ska3-core ska3-flight ska3-perl
mamba uninstall ska3-core ska3-flight ska3-perl
conda update --override-channels -c  https://cxc.cfa.harvard.edu/conda/ciao jpeg
conda install -c https://cxc.cfa.harvard.edu/conda/ciao   ciao sherpa ds9 ciao-contrib caldb_main marx
```

I forgot to say that sherpa also changes, ciao uses sherpa 4.13.0

**Comment by jeanconn** [comment]
Right, the issue IIRC, is that most of the Perl packages are built manually as one big conda package with no real proper dependency evaluation.  So confirming conda satisfies install dependencies seems like it wouldn't be enough.  "test splat" would be running the splat code (or maybe aca_movie) for the aca_egse using the modern Perl.  But like I said, probably not a real lien if it didn't work if we could just leave an old environment hanging around for that use case.

**Comment by javierggt** [comment]
For the record: the original reason for this request was to be able to install Ska in the same environment as CIAO. Updating jpeg was the only requirement to get it to work on OS-X. As it turns out... fixing the packages to make things work on linux was more complex, since some packages in the CIAO distribution have dependencies that are impossible to solve as they are.

Considering that (for now) there is no requirement that Ska and CIAO must be in the same environment, I dropped the matter.
