### ISSUE TITLE
Add chandra_models to skare3? 

### ISSUE THREAD

**Issue by jzuhone** [sot/skare3#654]
ACIS would use `chandra_models` to automagically grab model specifications (and thus be in sync with the FOT thermal review) if this package were part of ska.

**Comment by jeanconn** [comment]
I was thinking that you really want to do this via xija's get_model_spec and that just syncing the repo of chandra_models that we now keep up-to-date in /proj/sot/ska/data gets you there?

**Comment by taldcroft** [comment]
Exactly, I put in all this machinery to enable doing this in a way that is independent of GitHub and instead uses the "configured" ska data.

**Comment by javierggt** [comment]
I'm going to close this issue now, since the answer to the question seems to be "no"
