### ISSUE TITLE
Update core package astropy to 4.3.1

### ISSUE THREAD

**Issue by taldcroft** [sot/skare3#686]
Update package `astropy` to version 4.3.1.  (Note that 4.3.0 got skipped for technical reasons).

This includes some good stuff (https://docs.astropy.org/en/v4.3.1/whatsnew/4.3.html):

- Changes in the Time and IERS leap second handling (the pesky leap second problems on GRETA should be fixed)
- Support for multidimensional and object columns in ECSV
- Support for hiding / showing columns in a Table (I really wanted this for the ER finding notebook)

Ideally put this in the next ska3-flight and ska3-matlab releases.

**Comment by javierggt** [comment]
Installing astropy required the following updates:
- astropy-4.3.1
- ca-certificates-2021.7.5
- certifi-2021.5.30
- intel-openmp-2021.3.0
- mkl-2021.3.0
- mkl-service-2.4.0
- mkl_fft-1.3.0
- mkl_random-1.2.2
- numexpr-2.7.3
- numpy-1.20.3
- numpy-base-1.20.3
- openssl-1.1.1k
- pyerfa-2.0.0
- scikit-learn-0.24.2
- scipy-1.6.2
