### ISSUE TITLE
Recommend using --channel instead of editing .condarc

### ISSUE THREAD

**Issue by taldcroft** [sot/skare3#69]
I have had a number of problems where `conda` hangs for a while on the `icxc` channel URL when I'm doing stuff unrelated to Ska and am not on the VPN.  In general global channel defaults are just a little scary to me because you tend to not know where things are coming from (explicit is better than implicit).  To that end I made some edits.

@jeanconn - please review and close this issue if you concur.

https://github.com/sot/skare3/wiki/Ska3-runtime-environment-for-users/_compare/cb7f0f0ce5e735cf779489c342002856462abcce...dd29c907872600ffd7ff7ad86ff8845b47d7bfa9

**Comment by jeanconn** [comment]
Fine by me.

**Comment by jeanconn** [comment]
Not sure about adding the channel vs general global channel defaults with regard to setting your mind at ease unless you combine with the --override-channels option.

**Comment by taldcroft** [comment]
Well basically I just want `defaults` as my default channel.  If that fails to find something then start adding channels.  But what I don't want is to have it looking in ska3-conda and hanging unless I'm really doing a ska3 operation.  BTW, I even had a weird thing where I was installing pytest-astropy (or something like that) and ended getting half the packages from ska3-conda.  Not what I wanted.

I don't see how --override-channels helps anything since (I think) it means I have to always remember to opt out of my .condarc except on the very rare occasions when I am managing my ska environment.

**Comment by jeanconn** [comment]
"BTW, I even had a weird thing where I was installing pytest-astropy (or something like that) and ended getting half the packages from ska3-conda. "

Not that weird where on the linux side those test packages weren't built for our version of whatever (numpy?), so they are in skare3 for linux and osx along with astropy.
