### ISSUE TITLE
Add package fot-matlab to ska3-flight and ska3-flight-latest

### ISSUE THREAD

**Issue by jeanconn** [sot/skare3#765]
Add package fot-matlab to ska3-flight and ska3-flight-latest

**Comment by jeanconn** [comment]
I think the fot-matlab addition to ska3-flight-latest update probably got lost in rebase (in 2022.5 but not in 2022.6) but should be fine.

**Comment by jeanconn** [comment]
It still isn't in ska3-flight-latest.  I don't know if it needs to be?

**Comment by javierggt** [comment]
It is since 2022.6

**Comment by jeanconn** [comment]
Great.  I mean it wasn't *in* 2022.6 from https://github.com/sot/skare3/pull/860/files# but looks like it is in master so that's great (I think).  I don't think it will hurt.
