### ISSUE TITLE
Update text in ska3 release PR description

### ISSUE THREAD

**Issue by taldcroft** [sot/skare3#779]
In the automatic PR message for a new Ska release, "ska3-flight 2022.2 will be promoted to flight conda channel and installed on HEAD and GRETA Linux after this week's loads are approved." should be more like "ska3-flight 2022.2 will be promoted to flight conda channel and installed on HEAD and GRETA Linux at a time outside of the load review cycle."

Since FSDS is not tied to load review, all we do now is not promote between when loads are released and when they are approved.

**Comment by javierggt** [comment]
This has been fixed for a while.
