### ISSUE TITLE
Document ipython startup file setup

### ISSUE THREAD

**Issue by taldcroft** [sot/skare3#79]
It used to be:
```
You will also need to update the profile startup file which gets executed when
you start IPython.  The new version works with both the new and older IPython.
cp ~/.ipython/profile_default/startup/10_define_impska.py{,.bak}
cp /proj/sot/ska3/flight/include/cfg/10_define_impska.py ~/.ipython/profile_default/startup/</verbatim>
```
Not sure what was done to support Bill, but this could be changed to a step in the user guide to just copy/paste some text from the user guide into the right user file.

**Comment by taldcroft** [comment]
FYI I updated https://occweb.cfa.harvard.edu/twiki/bin/view/Aspect/SkaPython3 to just point to the Ska3 for users guide, and then added a link in the users guide to point back to SkaPython3 for hints on migration etc.

**Comment by jeanconn** [comment]
For Bill, I just put the file at /proj/sot/ska3/flight/include/cfg/10_define_impska.py on chimchim.

**Comment by javierggt** [comment]
This issue is more than 2 years old. I think it was solved. And certainly the context changed.

**Comment by taldcroft** [comment]
See also: https://github.com/sot/eng_archive/pull/210 and updates today to the Ska3 for users wiki guide.
