### ISSUE TITLE
Update Ska analysis configuration setup docs

### ISSUE THREAD

**Issue by taldcroft** [sot/skare3#80]
This is out of date:
http://cxc.cfa.harvard.edu/mta/ASPECT/tool_doc/eng_archive/tutorial.html

**Comment by javierggt** [comment]
How is this a skare3 issue? Docs were updated anyway.

**Comment by taldcroft** [comment]
See also: https://github.com/sot/eng_archive/pull/210 and updates today to the Ska3 for users wiki guide.

**Comment by javierggt** [comment]
I see, but then I would say this is an eng_archive issue, not skare3.

In principle, we could track everything to skare3, but I do not see the point.

**Comment by taldcroft** [comment]
I agree, and was not arguing to re-open this. My comment was just informational. About tracking things here, I will say that this issue here today was inspiration to tidy up the ancient docs in eng_archive, so it worked!
