### ISSUE TITLE
Missing osx-64 build of acis_taco

### ISSUE THREAD

**Issue by taldcroft** [sot/skare3#81]

**Comment by jeanconn** [comment]
I don't think this is really a skare3 issue, but I take the point.

**Comment by jeanconn** [comment]
I've rsync'd the package reindexed.  My point was that there is no outstanding issue with code or process, and that "jean forgot to rsync this once" isn't going to be an issue that is closed via a PR.  If you want to capture it as a github issue, that's fine.
