### ISSUE TITLE
Update package jinja2 to 3.0.x ?

### ISSUE THREAD

**Issue by taldcroft** [sot/skare3#810]
Update package jinja2 to version 3.0.x

This apparently fixes the DeprecationWarning 
```
<template>:18: DeprecationWarning: 'soft_unicode' has been renamed to 'soft_str'
```
according to https://github.com/lektor/lektor/issues/928#issuecomment-904802369.

**Comment by javierggt** [comment]
That is correct, but the reason we have this version is because of some other incompatibility. I Do not remember which one now, but I can check.
