### ISSUE TITLE
Consider patch to flt_envs to set LANG to en_US.UTF-8.

### ISSUE THREAD

**Issue by jeanconn** [sot/skare3#82]
For the record (from separate email):
```
kadi: /proj/sot/ska3/flight/bin/python -c "import locale; print(locale.getpreferredencoding())"
UTF-8
kadi: env LANG="" /proj/sot/ska3/flight/bin/python -c "import locale; print(locale.getpreferredencoding())"
ANSI_X3.4-1968

Cron env vars:

unagi (CentOS-5):
SHELL=/bin/sh
USER=aca
PATH=/usr/bin:/bin
PWD=/home/aca
SHLVL=1
HOME=/home/aca
LOGNAME=aca
MAILFROM=xxx

kadi (CentOS-6):
SHELL=/bin/sh
USER=aca
PATH=/usr/bin:/bin
PWD=/home/aca
LANG=en_US.UTF-8
SHLVL=1
HOME=/home/aca
LOGNAME=aca
MAILFROM=xxx
```

**Comment by jeanconn** [comment]
@taldcroft I think this would probably be OK.  If LANG is supported/handled differently on other platforms (Windows) or if the standard changes we'll need to just evaluate that as it comes.

I don't see a super-rush on this; for example I don't think anything in the matlab tools is going to need to run anything in a shell that uses flt_envs.

**Comment by taldcroft** [comment]
Agreed on all points.

**Comment by javierggt** [comment]
This seems outdated. The first comment relates to CentOS 5 and 6, but we moved to CentOS 7 already. I think all the current systems give UTF-8.
