### ISSUE TITLE
Comments on Ska3 runtime environment for maintainers

### ISSUE THREAD

**Issue by taldcroft** [sot/skare3#85]
Here are some comments on my first try to go through building and installing a new package (chandra_aca 4.23).

Overall I think this needs to be split into two distinct parts:

### Part 1: Updating a single package (for Jean and Tom)

Up front, the exact things to type in order to update a single package (use chandra_aca and Chandra.Time as canonical noarch and arch packages).  Assume that everything is set up and the maintainer is doing things as aca.  

This includes:
- Decide if arch or noarch.  (Give instructions on finding recipe in skare3 repo and figuring it out).  For noarch do everything on linux, for arch add the steps of doing things also from zero.
- Getting to the right directory (skare3 git), git checkout master, git pull origin master
- Build the package on linux.  Note that since the instructions are hardwired, it doesn't simplify things much to use the `build_root` var.  (Esp. since the MacOSX instructions have a different build root, and then the pull from MacOSX has to use an explicit directory name anyway, unless you could use a single `build_root` prefix on both platforms.
- Build the package on MacOSX if necessary (arch).
- Test locally if desired / necessary.
- Rsync to the right places
- Rebuild indexes.
- Update target installations.

### Part 2: setting up the infrastructure (mostly for Jean)
 
All the rest

###  Setting up build env

- Is `conda install ska3_builder` still needed?
- The "For OSX we could use newer packages" discussion is somewhat confusing and mostly a digression from the final way things are now done.  So the `.condarc` setup is the same for linux and OSX.
- Steps should say to get into bash as aca on zero.  (Also on unagi?)

### Building locally

- "You can then install the new built package into a non-production environment using ..".  This assumes there is some non-production environment but doesn't give steps to create it.

### Updating the Ska-conda channel

- This should be broken down first as arch and non-arch packages.  (How to easily tell?)  I started with the MacOSX production build for chandra_aca, then to realize it is noarch and I could do it on unagi.
- The rsync command for MacOSX does not work because it cannot see kadi without VPN.  Need to reverse the process and pull from unagi.

### GRETA syncing (if required)

But there **IS** access to icxc, so why this section?

At the end there are no docs on what to do next, namely update the `ska3-flight` metapackage within `skare3`.

**Comment by taldcroft** [comment]
In fact the Part 1 and Part 2 should be completely separate documents.  Part 1 is routine maintenance and package updates, Part 2 is developer docs on setting up the maintenance environment.

**Comment by jeanconn** [comment]
Good issue!

Regarding arch vs noarch.  I disagree about figuring it out.  I think we should just build the package on unagi and then see what was made.


> Is conda install ska3_builder still needed?

Not after you have an environment.  It is still holding "conda" as I've mentioned so it needs to be installed mostly as a metapackage.

> Steps should say to get into bash as aca on zero. (Also on unagi?)

Wasn't sure if we could change the aca shell at this point on unagi without blowing things up.

> "You can then install the new built package into a non-production environment using ..". This assumes there is some non-production environment but doesn't give steps to create it.

I thought we assumed that from the User setup docs but not sure how to reference.


> At the end there are no docs on what to do next, namely update the ska3-flight metapackage within skare3.

This is somewhat mentioned in the metapackage notes

https://github.com/sot/skare3/wiki/Ska3-runtime-environment-for-maintainers#metapackages

but could obviously be more clear.  Part of the problem as I've said was that I'm not sure which page this belongs on.

Regarding the GRETA rsync directions; I wasn't sure where to put them.  icxc is visible from chimchim but I wasn't sure if it was useful to have that rsync option available.

**Comment by jeanconn** [comment]
> I think we should just build the package on unagi and then see what was made.
> 
> Yes, that is a better way. So the instructions need to just say that. Right now it is framed as "If you are building on linux, do this, if MacOS, do that".

And actually, since we have more control over the environment on the 'zero' osx system as the aca user, that might be the easier starting platform.

> I thought we punted completely on ska3_builder as an installed package and were just running out of skare3 git repo.

ska3_builder is now a metapackage that installs the things that you actually need in your environment to build packages *besides* being in the skare3 repo:
 
https://github.com/sot/skare3/blob/0faced188180563e46227f14ec291cc709d9bea7/pkg_defs/ska3_builder/meta.yaml#L21

I can rename the metapackage if ska3_builder is getting confusing.

**Comment by javierggt** [comment]
This is outdated. If we want an issue about the newer docs. We open another one.
