### ISSUE TITLE
Remove $SKA/lib from LD_LIBRARY_PATH

### ISSUE THREAD

**Issue by javierggt** [sot/skare3#856]
**Description**

In RH8, there is a conflict between the `libcrypto.so.1.1` library in the conda env and the one in `/usr/lib64` (#854 ).

The issue can be traced to the presence of `$SKA/lib` in `$LD_LIBRARY_PATH` ([this line](https://github.com/sot/skare3/blob/master/pkg_defs/ska3-template/bin/flt_envs#L69)). I do not think we need `$SKA/lib` in `$LD_LIBRARY_PATH`. Everything works if one sets up the environment with conda (see below).

This is not fixed by installing git in the conda env.

What other alternative is there?

**To Reproduce**

on RH8 and within a local git repo:

```
jgonzale skare3 $ source /proj/sot/ska/jgonzalez/miniconda3/envs/ska3-flight-rh8/bin/ska_envs.sh
jgonzale skare3 $ git pull
/usr/bin/ssh: symbol lookup error: /usr/bin/ssh: undefined symbol: EVP_KDF_ctrl, version OPENSSL_1_1_1b
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Expected behavior**

Git should work.

**Additional context**

there is no issue if I setup the environment using conda:
```
eval "$(/proj/sot/ska3/flight/bin/conda shell.bash hook)"
git pull
```

**Comment by jeanconn** [comment]
The other alternative is probably to alias git to "env LD_LIBRARY_PATH="" git" like I've done with emacs, but I agree something like that should only be a fallback if other plans fail.
