### ISSUE TITLE
Absolute path no longer supported for `data_files` in setup.py

### ISSUE THREAD

**Issue by taldcroft** [sot/skare3#893]
I discovered this by installing the latest miniconda (conda 4.12.0) and using the established pattern for installing `task_schedule.cfg` to the share directory:
```
if "--user" not in sys.argv:
    share_path = os.path.join(sys.prefix, "share", "kalman_watch")
    data_files = [(share_path, ['task_schedule.cfg'])]
else:
    data_files = None
```

Alas the `task_schedule.cfg` file got installed to `site-packages/export/tom/....` in the distribution. Doing this absolute file install was never a great idea, and going forward we'll need a different way.

See https://setuptools.pypa.io/en/latest/userguide/datafiles.html#non-package-data-files

**Comment by javierggt** [comment]
In astromon I just have this (relative path and no exception fo `--user`:

```
data_files = [(
    os.path.join('share', 'astromon'),
    ['task_schedules/task_schedule_update.cfg']
)]
```
https://github.com/sot/astromon/blob/master/setup.py#L19

**Comment by javierggt** [comment]
I have not tried with newer python, but in our current setup it installs in the right place.

**Comment by taldcroft** [comment]
@javierggt - yes, now I see that your setup installs the file as expected, so nothing is likely to break in the future. 👍 

Good catch also on allowing this even for a `--user` install. The only minor caveat is that this puts the task schedule file in a place where `task_schedule3.pl` can't find it. In practice this is not a real issue since the console scripts in `bin` are also not in the path.

Even though this idiom of putting task schedule files in a common `share` directory still works, I'll stand by my opinion that this practice should be deprecated in favor of putting them in the package. It just makes more sense and fits in with how the Python packages recommend doing things.

**Comment by taldcroft** [comment]
@jzuhone - I see that `data_files` is used in `acis_thermal_check`: 
https://github.com/acisops/acis_thermal_check/blob/89befa36c36bb4b43a524ab2f0968b753fc89ef5/setup.py#L33

This usage confuses me because the data files in question are being installed within the package via `MANIFEST.in` and `include_package_data=True`.  From my reading of the [data_files docs](https://packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/#data-files) the existing `data_files` directive should be installing files to `(sys.prefix)/templates` and `(sys.prefix)/data`, but I don't see any files there in my local Ska.

So maybe just delete the `data_files=..` line?

**Comment by taldcroft** [comment]
Re: https://github.com/sot/task_schedule/pull/22#pullrequestreview-1065551394
> I'm more worried about other side effects of limiting how packages can write to share or data

@jeanconn - you would need to take this up with the Python Packaging Authority in general, but for Ska do you have a concrete example?

I note that in all the sot repos, there are only a few uses of `data_files` for anything except task schedule config files.
```
# Modern way: install script as `acis_taco_make_esaview_data.py`
acis_taco/setup.py-    share_path = os.path.join(sys.prefix, "share", "acis_taco")
acis_taco/setup.py:    data_files = [(share_path, ['share/make_esaview_data.py',
acis_taco/setup.py-                                'task_schedule.cfg', 'task_schedule_occ.cfg'])]

# ltt_bads.dat is orphaned and is not really useful any more. In any case it should
# either be declared mutable and live in $SKA/data or immutable and be in the package.
kadi/setup.py:    data_files = [(share_path, ['task_schedule_cmds.cfg',
kadi/setup.py-                                'task_schedule_events.cfg',
kadi/setup.py-                                'ltt_bads.dat'])]

# Modern way: install scripts as `(sys.prefix)/bin/mica_*`
mica/setup.py-    share_path = os.path.join(sys.prefix, "share", "mica")
mica/setup.py-    scripts = [str(script) for script in Path('scripts').glob('update_*.py')]
mica/setup.py:    data_files = [(share_path, scripts + ['task_schedule.cfg'])]

# This will be Javier's problem to fix when setuptools no longer supports data_files. :-)
kadi-apps/setup.py-    root = Path(__file__).parent
kadi-apps/setup.py-    static_dest = Path('share') / 'kadi_apps' / 'static'
kadi-apps/setup.py:    data_files = {}
kadi-apps/setup.py-    all_files = [(s, p) for s in root.glob('**/static') for p in s.glob('**/*')]
kadi-apps/setup.py-    for s, p in all_files:
kadi-apps/setup.py-        if not p.is_file():
kadi-apps/setup.py-            continue
```

**Comment by taldcroft** [comment]
I do note that the latest setuptools 63.4.2 does still support `data_files` and we don't know when, if ever, the deprecation will result in `data_files` not being supported.

**Comment by taldcroft** [comment]
However, the absolute path `sys.prefix` used in a number of repos does NOT correctly install the data files:
```
aca_hi_bgd/setup.py:    share_path = os.path.join(sys.prefix, "share", "aca_hi_bgd")
aca_weekly_report/setup.py:    share_path = os.path.join(sys.prefix, "share", "aca_weekly_report")
acis_taco/setup.py:    share_path = os.path.join(sys.prefix, "share", "acis_taco")
eng_archive/setup.py:# Install following into sys.prefix/share/eng_archive/ via the data_files directive.
eng_archive/setup.py:    share_path = os.path.join(sys.prefix, "share", "eng_archive")
jobwatch/setup.py:    share_path = os.path.join(sys.prefix, "share", "jobwatch")
mica/setup.py:# into sys.prefix/share/mica/ via the data_files directive.
mica/setup.py:    share_path = os.path.join(sys.prefix, "share", "mica")
perigee_health_plots/setup.py:    share_path = os.path.join(sys.prefix, "share", "perigee_health_plots")
```
These should all be fixed by removing `sys.prefix` from the `os.path.join`.

**Comment by taldcroft** [comment]
>  For our stuff, if we had a real need I suppose this could also be configured via the conda packaging.

I think that `pip install .` should correctly install all of our packages. I do use this in dev environments frequently.

**Comment by taldcroft** [comment]
I opened PR's to fix each of these. @jeanconn can you have a look?

**Comment by taldcroft** [comment]
When all of these PR's are merged we can close this issue, which technically deals with absolute paths and not the bigger concept of `data_files` itself.

**Comment by javierggt** [comment]
@taldcroft, I read again the PyPA user guide and I do not interpret it the same way you do. What I interpret is: if your package expects data, then install it with the package. To me, the question is if the data is going to be used by this package or it is going to be shared with other packages.

I doubt the installing share is ever going to be disabled.

You called this a "philosophical" question, and we are not going to argue endlessly about it. Having said that, I don't think it is not philosophical. Every operating system has their way to share data between apps, and forcing users to resort to something like exec('python -m module ...') and capture the output does not seem like a reasonable general solution to me. Unless you show me something that says that the shared folder is being deprecated in Linux, not just python, I very much doubt it will disappear, even from python installations.

Absolute paths are clearly a bug.

**Comment by taldcroft** [comment]
@javierggt - I agree with you on the general point of a need for sharing data between apps. 

The philosophy relates to this *specific* use of `share`, which is defining how a package (e.g. `kadi`) wants its cron processing performed. In my mind the `kadi` package owns everything about that and in effect `kadi` is calling `task_schedule.pl` to run itself as a cron job. So I think of `task_schedule_events.cfg` as package data because nothing beside kadi (running itself via task_schedule) uses that. 

Likewise `ltt_bads.dat` is not used by any other app, it was put there wit the misguided notion that by being in `share` it might be permissible to edit that file. In practice it didn't happen and was a poor idea to start.

You have an excellent point about the horrible `python -m module` code. I realize now that can be done cleanly and idiomatically with [pkgutil.get_data](https://docs.python.org/3/library/pkgutil.html#pkgutil.get_data).

**Comment by taldcroft** [comment]
@javierggt - About deprecation this information seems fairly unambiguous:
https://setuptools.pypa.io/en/latest/userguide/datafiles.html#non-package-data-files

>  It also does not use the word "deprecate"

From https://setuptools.pypa.io/en/latest/references/keywords.html:
<img width="808" alt="image" src="https://user-images.githubusercontent.com/348089/183688030-c0cdf2db-7b5f-47b8-9146-179056ea8529.png">

I see that https://packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/#data-files still talks about this option as if it were not deprecated, but I suspect that is an oversight. One can see the effort to deprecate / avoid `data_files` by removing reference to it here in an example:
https://github.com/pypa/setuptools/pull/2833

So it is happening. Maybe because `setuptools` is so widely used they will never make the last step of actually removing `data_files`, but that doesn't change that the PyPA considers it to be avoided. I personally don't care, except that I prefer to not use deprecated functionality where possible. So @jeanconn could be on the right track about using conda if we *need* to have non-package data, since that is explicitly supported.

**Comment by taldcroft** [comment]
Fixed by all the PR's that took out the absolute path from a number of setup.py files. The issue of where to install task schedule config files (in or out of package) is unrelated and at this time either way is fine.
