### ISSUE TITLE
Pin pip to 9.x

### ISSUE THREAD

**Issue by taldcroft** [sot/skare3#9]
Pip 10.0 finally removed the deprecated `--egg` option.  Our current process doesn't work without that, and I don't actually know how to maintain Py2/3 compatible namespace packages that do.

**Comment by jeanconn** [comment]
Makes sense.  I'm a little confused though about pinning the environment: do we need to pin pip in our build environment or our runtime environment? or do we just want to keep requirements on them the same?

**Comment by taldcroft** [comment]
This is done.
