### ISSUE TITLE
Consider adding nbdime

### ISSUE THREAD

**Issue by taldcroft** [sot/skare3#91]
[Nbdime](https://nbdime.readthedocs.io/en/latest/index.html) is a wicked useful and nice notebook diff tool.  It's available on conda-forge.  I've just been hand-installing, but maybe this should be a standard component.  Not clear on level of effort, and certainly not an immediate priority.

```
The following NEW packages will be INSTALLED:

    colorama:        0.4.0-py_0      conda-forge
    nbdime:          1.0.3-py36_1000 conda-forge

The following packages will be UPDATED:

    ca-certificates: 2018.03.07-0    defaults    --> 2018.10.15-ha4d7672_0 conda-forge
    openssl:         1.0.2l-0        defaults    --> 1.0.2l-0              conda-forge
```

**Comment by javierggt** [comment]
Do we still want this package? It seems there is no momentum for it.

**Comment by taldcroft** [comment]
Closing until we get some requests.
