### ISSUE TITLE
Process for merging PRs and package updates

### ISSUE THREAD

**Issue by taldcroft** [sot/skare3#93]
I'm not sure where we are at now with regards to the question of merging a PR prior to LR approval.  In theory we can merge, tag, and build packages to our heart's content, and we only need LR approval to finally make a new ska3-flight release and install.  We do get dinged in the unlikely event of something cropping up in review.  If that happens we can do a bug fix release or (worst case) revert the PR and delete the tag.

It seems like integration testing and managing the process is easier if we can get everything into master and have a package to conda install (though a pip install works fine too).  In fact if there is more than one PR for a package going into a release it is quite inconvenient to test them all together with merging into some branch.

**Comment by jeanconn** [comment]
Yes, this is why I'm nagging on tags (which still work in our current build process even if they aren't on master, but it seems more correct to only tag on master).

**Comment by taldcroft** [comment]
@jeanconn and @taldcroft discussed this today and agreed that merging a PR (and tagging and package building) prior to LR approval is OK.  The "process for maintainers" wiki page was updated to reflect this process.

**Comment by jeanconn** [comment]
You've updated the "process for maintainers" in a way that makes sense to me, but if I end up back on this issue these notes should help me:

I agree that merging an individual package PR prior to LR approval is fine.

With regarding to PRs that contain edits to the meta.yaml for ska3-flight, those can still be merged before load review approval, but with the awareness that one cannot blindly rsync ska3-flight built metapackages into the flight package repository, and that ska3-flight metapackages should only be installed in the flight/ska3-conda repo after approval.

**Comment by taldcroft** [comment]
@jeanconn - I've put a version of the second note into the wiki, and you should consider the wiki (and not issues) as the right place to capture all relevant information about process.
