### ISSUE TITLE
missing pyqt in ska3-core-latest?

### ISSUE THREAD

**Issue by jskrist** [sot/skare3#969]
the ska3-core package contains pyqt, but the ska3-core-latest does not.  It's possible that this is by design, but it caused an issue in the Python trunk area on windows.  pyqt was not being updated because the conda update command was referencing the ska3-core-latest package.

**Comment by javierggt** [comment]
yes, this might be a bug. I have to admit that we never test ska3-latest, but I guess we should, because it often is not right.

The test should be that replacing ska3-core by ska3-core-latest should be a no-op (so this ticket is the partner of #967)

**Comment by javierggt** [comment]
Fixed in 2023.1
